feat(fe): notice detail page
skkuding/codedang pull request #1078
Opened 2023-12-28 03:19 UTC by dayongkr

### Description
<img width="1392" alt="Screenshot 2023-12-28 at 12 14 05 PM" src="https://github.com/skkuding/codedang/assets/50468628/222e728a-7578-4d76-883d-65db1aac1f03">

<img width="1392" alt="Screenshot 2023-12-28 at 12 14 07 PM" src="https://github.com/skkuding/codedang/assets/50468628/59a82631-1747-490c-8ace-2efbeaa9b9eb">

<img width="457" alt="Screenshot 2023-12-28 at 12 15 54 PM" src="https://github.com/skkuding/codedang/assets/50468628/9dbab984-ec08-4bc1-bf46-3892953b99ef">

- notice list page에서 notice 클릭시 page query도 같이 넘겨줘서 List 버튼 누를 시 최대한 이전에 보고 있던 목록 유지
- 영어가 기본인 서비스에 맞게 이전, 다음이라는 말을 prev, next로 변경
- notice layout 상하 패딩 추가

close #1072

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-12-28 03:50 UTC, dotoleeoak commented on frontend-client/app/layout.tsx
> +const manrope = Manrope({ subsets: ['latin'], weight: ['400', '600'] })
혹시 한글 글꼴은 적용 안되어있나요?

2023-12-28 03:55 UTC, dotoleeoak commented on frontend-client/app/notice/_components/NoticeTable.tsx
> +  ]
지금은 title 글씨만 클릭이 가능한데, 셀 아무 곳이나 클릭해도 페이지 이동이 가능하면 좋겠어요

2023-12-28 05:03 UTC, aintbe commented
![image](https://github.com/skkuding/codedang/assets/83803824/2093e731-103d-4467-a549-4b5cb36da739)
한글 폰트 적용이 아직 안 되는 것 같아요!ㅠㅠ

2023-12-28 05:05 UTC, aintbe requested changes

2023-12-28 05:05 UTC, aintbe commented on frontend-client/app/layout.tsx
> +import { Manrope, Noto_Sans } from 'next/font/google'
한국어 폰트 적용하려면 NotoSansKR을 써야 합니다!! 수정해주세요~

2023-12-28 05:17 UTC, dayongkr commented
> ![image](https://private-user-images.githubusercontent.com/83803824/293140568-2093e731-103d-4467-a549-4b5cb36da739.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDA4NTQsIm5iZiI6MTcwMzc0MDU1NCwicGF0aCI6Ii84MzgwMzgyNC8yOTMxNDA1NjgtMjA5M2U3MzEtMTAzZC00NDY3LWE1NDktNGI1Y2IzNmRhNzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA1MTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMWI4OGFiODZkZDJjMTkxZGY4NWI0ZGNlYjYxODQ3ZmY1NTVkMzcwN2ExYWNhMmMxNWFlM2Y4MWQ4YzYzNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AR0ufcTaUYHlb3Zue5aWb4hL1_wiHn5Yu7NtCHtJcsE) 한글 폰트 적용이 아직 안 되는 것 같아요!ㅠㅠ

적용 됐습니다!

2023-12-28 08:24 UTC, dotoleeoak commented on frontend-client/app/layout.tsx
> +      <body>
이렇게 하면 영어도 Noto Sans KR 적용될 거라서, manrope 먼저 적용해야 한글만 Noto Sans KR 적용될 거 같아요

2023-12-28 08:43 UTC, dayongkr commented on frontend-client/app/layout.tsx
> +      <body>
저거는 css 변수 정의된 class 가져온거고 폰트는 tailwind의 font-sans속성 앞에 추가해서 적용했어요! tailwind 설정 파일 보시면 됩니다!

2023-12-28 10:20 UTC, jihorobert approved these changes
수정사항 확인했습니다

2023-12-28 23:42 UTC, dotoleeoak requested changes
아직 notice 리스트 불러오는 부분만 봤는데, 로직이 조금 복잡하다고 생각해서 주석은 직접 적어서 커밋했습니다. 추가로 수정 필요한 부분이 있어 보여서 리뷰 남겨요.

2023-12-28 23:42 UTC, dotoleeoak commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
이 부분 수정 필요할 것 같습니다 (FIXME로 주석 달아뒀어요)

2023-12-28 23:42 UTC, dotoleeoak commented on frontend-client/app/notice/page.tsx
>      currentPage !== currentTotalPages || currentTotalPages > maxPagesPerSlot // if currentPage is last page and currentTotalPages is less than maxPagesPerSlot, there is no next page
이 부분 이해를 못했는데, `currentPage < currentTotalPages`만 확인하면 안되나요?

2023-12-29 02:48 UTC, dayongkr commented
> 아직 notice 리스트 불러오는 부분만 봤는데, 로직이 조금 복잡하다고 생각해서 주석은 직접 적어서 커밋했습니다. 추가로 수정 필요한 부분이 있어 보여서 리뷰 남겨요.

이전 vue 프로젝트 참고해서 만들었는데 아무래듀 pagination 구현하려면 슬롯 단위로 notice를 불러와야 하다보니깐 로직이 복잡해졌습니다! 이따가 확인하고 리뷰 재요청하겠습니다!

2023-12-29 09:25 UTC, dotoleeoak requested changes

2023-12-29 09:25 UTC, dotoleeoak commented on frontend-client/app/notice/[id]/page.tsx
> +        dangerouslySetInnerHTML={{ __html: content }}
이거 혹시 sanitizing 적용 가능할까요?

2023-12-29 09:25 UTC, dotoleeoak commented on frontend-client/app/notice/layout.tsx
> +    </div>
실제 컨텐츠가 담긴 `div` element가 중첩이 많이 된 거 같은데 조금 줄여보는 거 어떨까요?
(`body > div > div > main > div > div`)

<img width="1473" alt="image" src="https://github.com/skkuding/codedang/assets/19747913/3b6ce3e1-de5c-4903-96ac-b2ee66d09bba">

2023-12-29 09:25 UTC, dotoleeoak commented on frontend-client/app/notice/page.tsx
> +    currentTotalPages > maxPagesPerSlot // if currentPage is last page and currentTotalPages is less than maxPagesPerSlot, there is no next page
이 부분 로직이 어떻게 되나요?

2023-12-30 12:13 UTC, dayongkr commented
@dotoleeoak  @aintbe  요청사항 확인된 것들은 승인부탁드립니다~

2023-12-30 12:52 UTC, dotoleeoak commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
@dayongkr 이 부분 수정 안됐는데 확인 부탁드려요

2023-12-31 01:23 UTC, dayongkr commented
layout 때문에 다른 작업들이랑 계속 충돌나서 브랜치 머지할 때마다 고쳐주고 있는데 아직 리뷰 남은건가용?? @dotoleeoak  @aintbe

2023-12-31 03:57 UTC, dotoleeoak commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
@dayongkr 지금은 cursor를 데이터 마지막 값이 아니라 직접 계산하고 있는데, 이건 원래 cursor-based pagination 구현 방식이 아닙니다. 아이디가 1~50인 모든 데이터가 있다는 보장이 없고, 이렇게 구현하면 데이터가 중간에 삭제되어있는 경우 제대로 동작이 안되겠죠.
기존 slot의 데이터 중 마지막 값을 query로 불러와서 cursor로 넣는 것이 바람직한 구현 같아요. 기존 Vue 코드에도 그렇게 구현되어있을 거예요.

2023-12-31 04:08 UTC, dayongkr commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
아항 이해했습니다!

2023-12-31 04:18 UTC, dayongkr commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
이전에는 무조건 1페이지부터 검색해나가니깐 이전 slot의 마지막 페이지를 알고 있으니 cursor-based가 효율적인데 지금은 1페이지부터 시작하는 것이 아니라 2슬롯 3페이지로 접속할 가능성이 있는데 이런 경우엔 맨 앞 notice부터 1슬롯 5페이지(take=100)까지 다 불러와서 마지막 페이지가 뭔지 확인하고 cursor를 지정해야할 것 같은데 이러면 너무 비효율적일 것 같은데 어떻게 생각하시나요??

2023-12-31 04:19 UTC, dayongkr commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
추가로 이전 버튼을 눌러서 이전 slot으로 넘어갈 때도 위와 같은 상황이 발생할 것 같습니다!

2023-12-31 04:20 UTC, dotoleeoak commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
query의 cursor 값을 필수로 지정하고, 입력이 안되어있으면 에러 표시하는 건 어떤가요?

2023-12-31 04:24 UTC, dayongkr commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
혹시 offset과 cursor 둘다 선택해서 사용할 수 있으면 어떨까요? next 버튼 누를땐 cursor 사용하고 나머지는 offset을 사용하는 방향으로요!

2023-12-31 04:25 UTC, dotoleeoak commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
나머지 경우면, 사용자가 직접 URL 입력하는 경우인가요?

2023-12-31 04:26 UTC, dayongkr commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
일단 약속이 있어서 좀 더 고민해보고 말씀드릴게요!

2023-12-31 04:27 UTC, dayongkr commented on frontend-client/app/notice/page.tsx
> +    query.append('cursor', String(currentSlot * take * maxPagesPerSlot))
그 notice detail page에서 목록으로 가기 버튼을 누르거나 이전 slot으로 갈 경우도 포함입니다!

2024-01-01 03:23 UTC, dotoleeoak approved these changes

2024-01-01 04:07 UTC, aintbe approved these changes

2024-01-01 04:07 UTC, merged