1022 usercode temporary save
skkuding/codedang pull request #1080
Opened 2023-12-28 06:26 UTC by gyunseo

### Description

- closes #1022 
- `User`가 `Problem`을 풀 때, UserCode를 5초에 한번씩 저장하는 REST API를 구현했습니다.
- client의 `Problem` module에 추가했습니다.

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2024-01-02 07:44 UTC, cho-to commented on backend/prisma/migrations/20231228055523_user_problem/migration.sql
호옥시 migration 파일 5개 하나로 합칠 수 있을까요!

2024-01-02 07:48 UTC, cho-to commented on collection/client/Auth/Log In/Succeed.bru
> +    "password": "Useruser"
요거는 잘못들어간 것 같아서 빼주시면 감사하겠습니다!!

2024-01-02 08:09 UTC, SH9480P requested changes

2024-01-02 08:09 UTC, SH9480P commented on backend/apps/client/src/problem/user-problem.controller.ts
> +@UseRolesGuard(Role.User)
얘는 없어도 됩니다...
User인지 체크하는 guard같은데,
User인지 체크하기 전에 JWTAuthGuard로 로그인된 사용자인지 확인하는 절차가 선행됩니다.
로그인 된 사용자는 필수적으로 User 이상의 Role을 가지기 때문에 User의 role을 갖는지는 확인하지 않아도 됩니다.

2024-01-02 08:09 UTC, SH9480P commented on backend/apps/client/src/problem/user-problem.controller.ts
> +      this.logger.error(err.message, err.stack)
this.logger.error(err)만 하셔도 됩니다.
pino logger로 세팅한 이후에 변경된 사항입니다.
하단 logger도 변경해주세요.

2024-01-02 08:09 UTC, SH9480P commented on backend/apps/client/src/problem/user-problem.controller.ts
> +        throw new NotFoundException(err.message)
P2025로 외래키 참조 불가 exception을 처리하실거면,
repository.ts에서 user id랑 problem id 있는지 확인(findUniqueorthrow)하시는 로직이 불필요할 것 같아요.
그러면
```
err instanceof Prisma.PrismaClientKnownRequestError &&
err.name === 'NotFoundError'
```
여기도 없어도 되겠죠

2024-01-02 08:14 UTC, cho-to commented on backend/prisma/schema.prisma
> +model UserProblem {
저도 바꾸는게 더 좋을 것 같아용

2024-01-02 08:24 UTC, cho-to commented on backend/apps/client/src/problem/problem.repository.ts
> +  ): Promise<Partial<UserProblem>> {
저도 upsert 사용하면 더 깔끔할 것 같아요~~

2024-01-02 09:13 UTC, cho-to commented on backend/prisma/schema.prisma
> +}
제 생각에는
1. 두 방안 다 괜찮을 것 같습니다. 임시 저장 코드에 접근할 때 userID & ProblemID 쌍으로 접근할 경우가 많을 것 같아서 id 필드는 지워도 괜찮을 것 같아용 (제 생각)
2. 이름 재정의 하는 것도 괜찮을 것 같아요 ~!

2024-01-04 09:50 UTC, Jaehyeon1020 commented on backend/apps/client/src/problem/problem.repository.ts
> +      })
동일한 `userId`와 `problemId`를 가지는 UserProblem이 이미 존재하는지 확인하기 위한 목적이라면 findUnique를 사용하지 않아도 괜찮지 않을까요? findUnique를 미리 하지 않아도 밑에 `await this.prisma.userProblem.create`에서 동일한 `userId`와 `problemId`를 가지는 데이터가 있으면 예외가 발생합니다.

2024-01-10 14:05 UTC, SH9480P requested changes

2024-01-10 17:24 UTC, gyunseo commented on backend/apps/client/src/problem/dto/code-draft.response.dto.ts
> +}
그렇네요! 공식 문서 보고 이해했습니다 감사합니다 ㅎㅎ

2024-01-11 00:45 UTC, SH9480P approved these changes
고생하셨습니다~

2024-01-11 03:50 UTC, merged

2024-02-07 08:45 UTC, Jaehyeon1020 commented on backend/apps/client/src/problem/problem.repository.ts
> +        template: template.template as CodeDraftUpdateInput['template']
여기서 type으로 사용된 `CodeDraftUpdateInput`이 Client 내부에 정의된 클래스가 아닌 Admin의 @generated에서 import되고 있어서 Client 서버만 실행 후 사용하면 에러가 발생하고 있습니다. 수정 부탁드려요!

2024-02-07 08:45 UTC, Jaehyeon1020 commented on backend/apps/client/src/problem/problem.repository.ts
> +        template: template.template as CodeDraftUpdateInput['template']
@gyunseo

2024-02-07 08:45 UTC, Jaehyeon1020 commented on backend/apps/client/src/problem/problem.repository.ts
> +        template: template.template as CodeDraftUpdateInput['template']
hotfix 올려주시면 될 것 같슴다