feat(fe): navigation active link
skkuding/codedang pull request #1092
Opened 2023-12-28 11:48 UTC by jihorobert

### Description

- Nav bar 섹션별(Notice, Contest, Problem, Group) active link 구현
  - 클릭한 섹션의 text 색깔 primary color로 변경
    - usePathname() 이용
    - NavLink 컴포넌트 생성 후 Header 파일에서 활용
    
  
<img width="1728" alt="스크린샷 2023-12-28 오후 8 44 07" src="https://github.com/skkuding/codedang/assets/59248080/fe85c1b2-12da-4cb7-bc23-96a9d7ae7208">

Closes #1089
---

### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [X] Ideally, include relevant tests that fail without this PR but pass with it.

2023-12-28 22:11 UTC, dotoleeoak commented on frontend-client/app/_components/NavLink.tsx
> +      }`}
사소하긴 한데 `cn` 함수로 적는 게 더 깔끔한 것 같습니다!

```suggestion
      className={cn(
        'text-lg hover:opacity-60',
        pathname === href && 'text-primary'
      )}
```

2023-12-29 04:52 UTC, dayongkr requested changes

2023-12-29 04:52 UTC, dayongkr commented on frontend-client/app/_components/NavLink.tsx
> +        pathname === href ? 'text-primary' : ''
<img width="766" alt="Screenshot 2023-12-29 at 1 48 39 PM" src="https://github.com/skkuding/codedang/assets/50468628/fd912413-4124-476a-9ef7-215cf0f92140">

지금처럼 구현하면 하위 주소가 있을시에 적용이 안됩니다! 따라서 포함이 되는지를 확인하는게 좋을 것 같아요!

```suggestion
        pathname.includes(href) ? 'text-primary' : ''
```

2023-12-29 05:34 UTC, dotoleeoak commented on frontend-client/app/_components/NavLink.tsx
> +        pathname === href ? 'text-primary' : ''
includes로 하면 뒤에 포함되어있어도 적용되지 않나요?
예를 들어서 /group/notice라는 링크도 notice에 적용이 될 거 같은데,
`includes()` 대신 `startsWith()` 쓰는 거 어떨까요?

2023-12-29 05:52 UTC, dayongkr commented on frontend-client/app/_components/NavLink.tsx
> +        pathname === href ? 'text-primary' : ''
앗 그 경우를 생각 못했네요! 그게 좋을 것 같습니다!

2023-12-29 05:56 UTC, jihorobert commented on frontend-client/app/_components/NavLink.tsx
> +      }`}
확인하고 적용했습니다!

2023-12-29 05:58 UTC, jihorobert commented on frontend-client/app/_components/NavLink.tsx
> +        pathname === href ? 'text-primary' : ''
그렇네요. 오늘안으로 확인하고 적용하겠습니다!

2023-12-29 06:58 UTC, jihorobert commented
@dotoleeoak @dayongkr 해당 내용들 반영했습니다!

2023-12-29 07:36 UTC, dotoleeoak approved these changes
좋습니다 👍

2023-12-30 11:31 UTC, dayongkr approved these changes

2023-12-30 11:33 UTC, merged