feat(be): add participants to contest api
skkuding/codedang pull request #1144
Opened 2024-01-05 09:39 UTC by mnseok

### Description

Closes https://github.com/skkuding/codedang/issues/1140

get contests API에 participants를 포함시켜 Return하도록 변경하였습니다.
contestRecord를 join하여 length를 얻고 난 이후 return 객체에는 포함되지 않도록 하였습니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-01-06 13:22 UTC, dotoleeoak requested changes
spec 파일도 확인하고 테스트 부탁드립니다!

2024-01-08 07:43 UTC, dotoleeoak commented on backend/apps/client/src/contest/contest.service.spec.ts
> +        upcoming: [{ ...upcomingContests[0], participants: 1 }]
`ongoingContests`에 `participants` field를 넣는 건 어떤가요?

2024-01-08 07:49 UTC, mnseok commented on backend/apps/client/src/contest/contest.service.spec.ts
> +        upcoming: [{ ...upcomingContests[0], participants: 1 }]
네 수정했습니다

2024-01-08 07:54 UTC, dotoleeoak approved these changes

2024-01-08 07:54 UTC, merged