1114 workbook problem api add accept rate
skkuding/codedang pull request #1150
Opened 2024-01-06 12:09 UTC by Lee-won-hyeok

### Description

problem의 related problems response dto를 수정하였습니다.

get group workbook problems 및 get group contest problems 요청 시 기존에는 problemID와 title, difficulty를 반환해 주었습니다.
여기에 acceptRate와 submissionCount를 추가하였습니다.

bruno collection의 client/problem 내의 assert 문서를 수정하였습니다.

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-01-06 12:15 UTC, dotoleeoak commented
PR 제목 커밋 컨벤션 맞춰서 수정 부탁드려요 🙂

2024-01-06 14:21 UTC, aintbe requested changes

2024-01-06 14:21 UTC, aintbe commented on .devcontainer/devcontainer.json
> +  "initializeCommand": "echo 'Hello World!'"
이 부분 실수로 넣으신 것 같은데, 이전 코드로 되돌려주세요!

2024-01-07 06:12 UTC, aintbe approved these changes
수고하셨습니다!

2024-01-08 05:50 UTC, merged