refactor(be): convert param-based endpoint to query-based
skkuding/codedang pull request #1178
Opened 2024-01-12 02:10 UTC by Jaehyeon1020

### Description

Close #740 

param-based로 되어있어 중복이 많았던 코드를 query-based로 전환하며 정리합니다.

### Additional context

** 작성중입니다

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2024-01-15 06:03 UTC, SH9480P commented
### 24.01.15 회의 중 나온 의견
- AuthGuard와 GroupMemberGuard에서 Open Space에 대한 요청인지 확인하고 처리하는 로직이 포함되어있기 때문에, GroupMemberGuard를 client에 전역으로 적용하고, AuthNotNeeded는 AuthNotNeededIfOpenSpace 정도로 이름을 바꾸어, 필요에 따라 각 모듈에 적용하는 것은 어떤지?

2024-01-15 06:04 UTC, SH9480P commented on backend/libs/auth/src/jwt/jwt-auth.guard.ts
>        return true
groupId가 undefined일 때와, groupId가 1일 때 모두 적용해야 할 듯 합니다.

2024-01-15 06:06 UTC, SH9480P commented on backend/libs/auth/src/jwt/jwt-auth.guard.ts
>        return true
GroupMemberGuard도 동일한 문제가 있습니다

2024-01-15 07:28 UTC, mnseok commented
`@UseGroupMemberGuardOrNoAuth()` 이름제안
`@UseOptionalGroupMemberGuard`는 어떨까요? query에 따라서 선택적으로 적용한다고 볼 수 있을 것 같아서요

2024-01-19 08:13 UTC, SH9480P requested changes
### Bruno 수정사항
- Get group contest by ID 항목이 불필요할 듯 합니다

2024-01-19 08:13 UTC, SH9480P commented on collection/client/Workbook/Get Workbooks/400: Invalid cursor value.bru
url path에 group이 포함되어있습니다

2024-01-19 08:13 UTC, SH9480P commented on collection/client/Workbook/Get Workbooks/400: Validation failed.bru
url path에 group이 포함되어있습니다

2024-01-19 10:01 UTC, Jaehyeon1020 commented on backend/apps/client/src/submission/submission.controller.ts
>        if (
서비스 코드에서 `findUniqueOrThrow()`를 사용하고 있고, 여기서 error name NotFoundError로 예외를 던지는데, 이 예외 처리를 위해서 추가해놓았습니다

2024-01-19 11:06 UTC, Jaehyeon1020 commented on collection/client/Contest/Get ongoing & upcoming contests/Succeed.bru
넵 좋은 것 같습니다!

2024-01-19 11:08 UTC, Jaehyeon1020 commented on collection/client/Problem/Get all problems/Succeed.bru
> -  - `submit-asc`, `submit-desc`
docs는 최상단 Succeed(Open Space)에 있어서 다른 docs와의 통일성을 위해서 제거했고, Assert는 다시 추가하는게 좋을 것 같아서 그렇게 하도록 하겠습니다!

2024-01-19 11:11 UTC, Jaehyeon1020 commented on collection/client/Submission/Get Contest Submission by ID/404: Nonexistent Contest.bru
네 기존에 잘 되어있지 않던 부분이 많아서, 별도 issue에서 해결하는 것이 좋을 것 같습니다.

2024-01-19 13:09 UTC, SH9480P commented
수정한 IdvalidationPipe를 사용하는 경우, number or undefined로 타입 지정을 할 필요가 있습니다

2024-01-19 14:10 UTC, SH9480P commented on backend/apps/client/src/announcement/announcement.controller.ts
> +        throw new ConflictFoundException(error.message)
exception 폴더에 정의된 exception class는 비즈니스 로직을 위한 것이고, 이를 컨트롤러 단에서 http status code를 담은 exception으로 변경하여 클라이언트에 전달합니다
그래서 conflictfound를 1차로 던지고 conflictexception을 2차로 던지는 것이 맞죠

그러나 그 전에, problem id와 contest id가 모두 들어오지 않는 경우를 비즈니스 로직에 포함시켜서 다루어야 하는가에 대한 의문이 있네요.
그래서 conflictfound 없이 conflictexception만 던지는 것도 괜찮을 것 같습니다

2024-01-19 14:21 UTC, Jaehyeon1020 commented on backend/apps/client/src/announcement/announcement.controller.ts
> +        throw new ConflictFoundException(error.message)
헉 네 감사합니다.. 그런데 problemId와 contestId가 모두 들어오지 않는 경우를 비즈니스 로직에서 다루지 않는다고 하면 어떤 식으로 처리하는게 적절할까요? 말씀해주신 ConflictException만 던진다는게 try문 내부에서 ConflictException을 던지고 catch문에서 잡아서 그대로 다시 throw하는걸 의미하는게 맞나요?

2024-01-19 14:33 UTC, SH9480P commented on backend/apps/client/src/announcement/announcement.controller.ts
> +        throw new ConflictFoundException(error.message)
음... try catch문 밖에서 한 번만 던지면 되겠죠?

2024-01-20 01:13 UTC, SH9480P reviewed
수고하셨습니다..
마지막으로 몇 가지 의논하고 PR 닫아도 될 것 같아요

1. problem ID와 contest ID 둘 다 들어오지 않아서 처리할 수 없는 요청의 경우 ConflictException 던지게 구현하셨잖아요? 409 에러가 의미하는 바와 같은 케이스로 볼 수 있을지 잘 모르겠습니다. 400 Bad request나 404 Not Found가 맞지 않나 싶네요.

2. Bruno에 Get group contest by ID 항목 불필요한 것 같아요.
![image](https://github.com/skkuding/codedang/assets/64393421/0e0e00a7-1cd4-463a-8819-e9ad63c6f379)

3. PR merge되면 프론트엔드 분들이 기존에 연결해둔 API를 많이 바꾸셔야 하니, 미리 고지하고 merge하는 건 어떠신지요?

2024-01-20 03:25 UTC, Jaehyeon1020 commented
1. 네 400 던지는게 더 적절할 것 같아서 그렇게 수정하였습니다.
2. 잘못 남아있네요 ㅠㅠ 삭제했습니다.
3. 네 오늘내일중으로 팀즈에 메세지 남겨놓으려고 합니다!
상세한 리뷰 감사합니다 ~~

2024-01-20 03:34 UTC, SH9480P approved these changes

2024-01-20 15:05 UTC, merged