527 admin notice api module
skkuding/codedang pull request #1188
Opened 2024-01-15 06:37 UTC by mnseok

### Description

Admin Notice 모듈을 만들었습니다.

create: groupManger혹은 그 상위인지 Roles Guard를 통해 검증 이후 생성하도록 작성하였습니다.

update: create와 마찬가지로 작성하였습니다.

delete: create와 마찬가지로 작성하였습니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-01-15 06:52 UTC, SH9480P commented on backend/apps/admin/src/notice/notice.resolver.ts
> +  async createNotice(
`admin.module.ts`에 Group Leader Guard가 전역 적용되어있습니다.
불필요한 UseGuard 데코레이터로 보이네요

2024-01-15 06:58 UTC, mnseok commented on backend/apps/admin/src/notice/notice.resolver.ts
> +  async createNotice(
넵 확인하고 수정했습니다!

2024-01-17 15:22 UTC, Jaehyeon1020 reviewed
Notice Read 기능은 원래 구현하지 않기로 하셨던건가요?

2024-01-18 03:47 UTC, SH9480P commented
> Notice Read 기능은 원래 구현하지 않기로 하셨던건가요?

필요합니다~
notice에 isVisible 속성이 있는데, manager가 보여줄지 말지 설정하는 속성입니다
client에서는 isVisible이 false인 것만 볼 수 있고, admin은 상관없이 전부 조회할 수 있어야 합니다
@mnseok

2024-01-18 04:14 UTC, SH9480P requested changes

2024-01-18 04:14 UTC, SH9480P commented on backend/apps/admin/src/notice/notice.service.ts
> +        isVisible: notice.isFixed,
수정 요망

2024-01-25 16:36 UTC, SH9480P commented
아직 작업중

2024-01-28 14:37 UTC, Jaehyeon1020 reviewed
Additional Context
1. 불필요한 DB 접근이 사라져 매우 좋은 것 같습니다 다른 모듈도 앞으로 이렇게 수정하면 좋을것같아요~!!
2. Notice 작성자의 username을 알고 싶다던지 하는 상황에서 추가적인 요청이 필요하지 않게 되어 좋은 것 같습니다!

2024-01-28 14:37 UTC, Jaehyeon1020 commented on collection/admin/Notice/Create Notice/NotFound.bru
> +  name: NotFound
내일 이야기해보고, 이름 정해지는대로 수정해주시면 좋을 것 같습니다!

2024-01-28 14:44 UTC, Jaehyeon1020 commented on collection/admin/Notice/Create Notice/NotFound.bru
> +  name: NotFound
GraphQL이라 반환되는 값이 달라질수도 있긴 한데 혹시 Assert는 지금 요청 query에 있는 필드들에 대해서는 추가해놓는게 좋을까요?

2024-02-01 08:59 UTC, cho-to approved these changes
-noticeId 통일
-assert 추가
만 추가되면 전 좋아요 ~~~~

2024-02-01 09:06 UTC, cho-to commented on backend/apps/admin/src/notice/notice.resolver.ts
> +}
신기해용

2024-02-03 17:03 UTC, SH9480P approved these changes

2024-02-04 14:26 UTC, merged