feat(be): implement admin announcement module
skkuding/codedang pull request #1270
Opened 2024-01-29 08:52 UTC by Lee-won-hyeok

### Description

#1047

Admin announcement 모듈을 구현하였습니다.
- Admin 권한을 통해 CRUD를 수행할 수 있습니다.

### Additional context
생성하려는 announcment의 problem Id, content 쌍이 이미 존재한다면 Duplicated Error를 발생시키고 있습니다. 이 때의 에러 메시지를 수정할 필요가 있어 보입니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-01-31 17:51 UTC, gyunseo requested changes
제가 코멘트 단 부분 수정해 주시면 감사하겠습니다!!

2024-01-31 17:51 UTC, gyunseo commented on collection/admin/Announcement/Create Announcement/Succeed.bru
> +}
[Bruno API DOCS Convention](https://www.notion.so/skkuding/Bruno-API-Docs-Convention-b65e02850c4048a3a87ef6c57eaa0a02?pvs=4)에 맞게 Bruno API 문서 수정 부탁드려요! 딴 문서들도 모두 마찬가지입니다.

2024-01-31 17:51 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.service.ts
> +    const announcement = await this.prisma.announcement.findFirst({
findFirst와 if문으로 에러가 있는지 확인하는 것도 좋지만, Prisma Client API로 제공되는 [findFirstOrThrow](https://www.prisma.io/docs/orm/reference/prisma-client-reference#findfirstorthrow)를 써서 에러 처리 로직을 더 간단히 하는 것도 괜찮을 것 같습니다!

2024-01-31 17:51 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.service.ts
> +    const problem = await this.prisma.problem.findFirst({
여기도 
> findFirst와 if문으로 에러가 있는지 확인하는 것도 좋지만, Prisma Client API로 제공되는 [findFirstOrThrow]> (https://www.prisma.io/docs/orm/reference/prisma-client-reference#findfirstorthrow)를 써서 에러 처리 로직을 더 간단히 하는 것도 괜찮을 것 같습니다!

2024-01-31 17:51 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.service.ts
> +    const announcement = await this.prisma.announcement.findFirst({
여기도 마찬가지입니다.
> findFirst와 if문으로 에러가 있는지 확인하는 것도 좋지만, Prisma Client API로 제공되는 [findFirstOrThrow](https://www.prisma.io/docs/orm/reference/prisma-client-reference#findfirstorthrow)를 써서 에러 처리 로직을 더 간단히 하는 것도 괜찮을 것 같습니다!

2024-01-31 17:51 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.resolver.ts
>    ) {
[GraphQL Exception](https://github.com/skkuding/codedang/pull/1267) PR을 지금 @SH9480P 세환님께서 작업 중이신데, 이를 기반으로 GraphQL resovler로 올라온 business 예외 처리 핸들링 코드가 조금 바뀔 거 같습니다. 이를 참고하여 예외 처리를 코들 작성해 주시면 감사하겠습니다. 현재는 resolver로 올라온 business exception 처리 코드가 작성돼있지 않은 것으로 보입니다.

2024-02-01 03:18 UTC, SH9480P commented on backend/apps/admin/src/announcement/announcement.resolver.ts
>    ) {
제 PR 관련하여 첨언하자면
client api에서 하던 대로 HTTP Exception 날려주시면 됩니다 이 외에 더 신경 쓰실 것 없게 구현할 예정입니다

2024-02-01 05:52 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.resolver.ts
>    ) {
@Lee-won-hyeok 방금 세환님과 얘기를 나누었는데, 원래 하던 대로 service code에서 올라온 business exception을 resolver에서 `try` `catch`로 잡아와서 exception을 handling하면 될 것 같웁니다. [딴 admin module의 resolver 코드들](https://github.com/skkuding/codedang/blob/main/backend/apps/admin/src/group/group.resolver.ts)을 참고해서 작성하시면 될 것 같습니다.

2024-02-01 09:09 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.service.ts
> +    const announcement = await this.prisma.announcement.findFirst({
죄송해요. `Create`의 경우는, [prisma client create api](https://www.prisma.io/docs/orm/reference/prisma-client-reference#return-type-3) 프리즈마 공식 문서를 참고하니, 따로 중복되는 경우를 예외처리 해 주지 않아서요. 본래 짰던 대로 하시면 될 거 같네요.

2024-02-01 09:11 UTC, gyunseo reviewed
죄송합니다. 어제 정신혼미 상태에서 리뷰하다 보니 조금 말이 안되는 코멘트를 하나 남겼었네요.

2024-02-01 09:11 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.service.ts
> +    const problem = await this.prisma.problem.findFirst({
여기는 problem table에서 원하느 problem record를 찾는 것이니, 여기서 findFirstOrThrow를 쓰는 게 맞을 것 같습니다.

2024-02-13 07:24 UTC, gyunseo requested changes

2024-02-13 07:24 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.service.ts
> +    await this.prisma.problem.findFirstOrThrow({
저희가 service layer에서 ORM API에서 나오는 PrismaClientKnownRequestError의 경우는, 서비스 코드에서 try catch로 묶어서 `business.exception.ts`에 정의한 익셉션을 의도적으로 발생하게 해주게 했어요.
그래서 findFirstOrThrow에서 record를 찾지 못할 경우는 service에서 EntityNotExistException을 throw하게 코드를 변경해 주세요.

2024-02-13 07:24 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.service.ts
> +      where: {
저희가 service layer에서 ORM API에서 나오는 PrismaClientKnownRequestError의 경우는, 서비스 코드에서 try catch로 묶어서 business.exception.ts에 정의한 익셉션을 의도적으로 발생하게 해주게 했어요.
그래서 findFirstOrThrow에서 record를 찾지 못할 경우는 service에서 EntityNotExistException을 throw하게 코드를 변경해 주세요.

2024-02-13 07:24 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.resolver.ts
> +        error instanceof PrismaClientKnownRequestError &&
서비스 코드에서는 PrismaClientKnownRequestError가 아닌, `business.exception.ts`에 정의한 exception만이 controller와 resolver로 올라오게 하기로 했습니다. 그래서 그것들을 상기 코드 처럼 if 문으로 잡아서 throw error.convert2HTTPException()으로 변환하게 했습니다.

2024-02-13 07:24 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.resolver.ts
> +        error instanceof PrismaClientKnownRequestError &&
서비스 코드에서는 PrismaClientKnownRequestError가 아닌, `business.exception.ts`에 정의한 exception만이 controller와 resolver로 올라오게 하기로 했습니다. 그래서 그것들을 상기 코드 처럼 if 문으로 잡아서 throw error.convert2HTTPException()으로 변환하게 했습니다.

2024-02-13 08:04 UTC, gyunseo requested changes

2024-02-13 08:04 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.service.spec.ts
> +      const res = await service.create(announcementInput)
현재 mocha test가 통과되지 않는데, mocha test가 모두 통과되게 test code 수정부탁 드립니다.

2024-02-13 08:04 UTC, gyunseo commented on backend/apps/admin/src/announcement/announcement.service.ts
> +  async create(
resolver 함수랑 이름이 동일하게 되도록 function name 수정 부탁드립니다.
다른 service 코드 내의 함수들도 동일하게 부탁드립니다.

2024-02-13 08:04 UTC, gyunseo commented on collection/admin/Announcement/Create Announcement/Succeed.bru
> +
<https://docs.codedang.com/intro/bruno.html>에 맞게 assert도 추가해 주세요!

2024-06-03 11:20 UTC, cho-to reviewed
혹시 리뷰 몇 개 남겼는데 봐주실 수 있을까요?!
무조건 고치라는 뜻은 아니니 한 번 보시고 의견 남겨주시면 감사하겠습니다 :)

2024-06-03 11:20 UTC, cho-to commented on collection/admin/Announcement/Create Announcement/Error: Duplicated Announcement.bru
> +  name: Error: Duplicated Announcement
혹시 그 에러 이름 양식 맞춰서 작성해주실 수 있을까요?
UNPROCESSABLE (1) (2) ... (에러 네임) 이렇게 적기로 저번 겨울 방학에 정했는데, 관련 회의록 찾아보고 있으면 드릴게요!

2024-06-03 11:20 UTC, cho-to commented on collection/admin/Announcement/Get Announcement/Succeed.bru
> +  |id|int|조회할 Announcement의 id|
앗 Args는 그 bruno schema 연동하면 args 다 보여주기 때문에 굳이 적으실 필요는 없어요!
그래도 수고하셨습니다 ... !!

2024-06-03 11:38 UTC, cho-to commented on apps/backend/apps/admin/src/announcement/announcement.service.ts
> +  async createAnnouncement(announcementInput: AnnouncementInput) {
여쭤봤는데.. 아직 group에 대해서 기획 확실히 정해진게 없어서 기획팀께 문의해보기로 하였습니다 🥹

2025-01-03 12:41 UTC, closed without merging