fix(be): replace problem order pipe from zodvalidator
skkuding/codedang pull request #1310
Opened 2024-02-05 07:11 UTC by mnseok

### Description

ZodValidator를 이용하여 Problem Order를 validation하던 것을
typescript의 enum을 이용하여 .include method를 활용하여 Validation

close #1164

### Additional context

Enum 말고 Class-validator를 활용하여 validation 할 수 있는 방법이 있다면 추천 부탁드립니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-02-05 08:32 UTC, Jaehyeon1020 requested changes

2024-02-05 08:32 UTC, Jaehyeon1020 commented on backend/libs/pipe/src/problem-order.pipe.ts
> +    console.log(ProblemOrderList, value)
테스트용으로 써놓으신거라면 삭제 부탁드립니다~

2024-02-05 08:32 UTC, Jaehyeon1020 commented on backend/apps/client/src/problem/problem.controller.ts
> +// import { ProblemOrder } from './schema/problem-order.schema'
잘못 들어간 주석이면 지워주세요~

2024-02-05 13:05 UTC, Jaehyeon1020 requested changes

2024-02-05 13:05 UTC, Jaehyeon1020 commented on backend/libs/pipe/src/problem-order.pipe.ts
> +  transform(value: unknown) {
```
transform(value: unknown) {
    if (!value) {
      return ProblemOrder.idASC
    } else if (!Object.values(ProblemOrder).includes(value as ProblemOrder)) {
      throw new BadRequestException('Validation failed')
    }
    return value
  }
```

transform 함수는 이런식으로 작성해보시는건 어떻게 생각하시나요?
Enum 파일에 ProblemOrderList와 isValidProblemOrder 함수 모두 삭제해도 괜찮은 방법이라 생각해보시고 수정 부탁드려요~

2024-02-05 13:05 UTC, Jaehyeon1020 commented on backend/libs/pipe/src/problem-order.pipe.ts
> +      throw new BadRequestException('Validation failed')
에러 메세지 조금 더 자세하게 적어주시면 좋을 것 같습니다!

2024-02-05 13:05 UTC, Jaehyeon1020 commented on backend/libs/pipe/src/problem-order.pipe.ts
> +    console.log(ProblemOrderList, value)
위의 transform 함수처럼 작성하시면 아예 삭제해도 무방할 것 같아요~

2024-02-12 17:34 UTC, cho-to commented on backend/libs/pipe/src/problem-order.pipe.ts
> +      throw new BadRequestException('Validation failed')
간단하게 `Problem-order validation failed` 이렇게만 적어도 괜찮을 것 같아요 ~~
원하시는 대로 적으셔도 괜찮을 것 같습니다!

2024-02-12 17:42 UTC, cho-to requested changes

2024-02-12 17:42 UTC, cho-to commented on backend/libs/types/src/problem-order.type.ts
enum 폴더 새로 생성하시면 problem.repository.ts , problem.service.ts 에 있는 import 경로도 수정해주시면 더 좋을 것 같습니다 !!!

2024-02-13 07:37 UTC, Jaehyeon1020 commented on backend/apps/client/src/problem/problem.service.ts
> +// import type { ProblemOrder } from './schema/problem-order.schema'
불필요한 주석이라면 제거해주세요~

2024-02-13 07:37 UTC, Jaehyeon1020 commented on backend/apps/client/src/problem/enum/problem-order.enum.ts
> +export const ProblemOrderList: ProblemOrder[] = Object.values(ProblemOrder)
ProblemOrderPipe에서 사용되고 있지 않은 것 같아서 제거해주셔도 될 것 같습니다!

2024-02-17 03:45 UTC, Jaehyeon1020 approved these changes
수고하셨습니다! 👍

2024-02-17 03:46 UTC, merged