1317 contest detail for user
skkuding/codedang pull request #1328
Opened 2024-02-07 04:57 UTC by gyunseo

### Description

`Get contest by ID` client API에 HTTP 요청을 했을 때, 요청 당시 로그인된 유저가 해당 contest에 가입 가능 여부도 Reponse에 표시되게 기능을 수정했습니다.

```JSON
{
  "id": 1,
  "title": "SKKU Coding Platform 모의대회",
  "startTime": "2024-01-01T00:00:00.000Z",
  "endTime": "2028-01-01T23:59:59.000Z",
  "group": {
    "id": 1,
    "groupName": "Example Group"
  },
  "_count": {
    "contestRecord": 13
  },
  "description": "<p>\n  대통령은 내란 또는 외환의 죄를 범한 경우를 제외하고는 재직중 형사상의 소추를\n  받지 아니한다. 모든 국민은 자기의 행위가 아닌 친족의 행위로 인하여 불이익한\n  처우를 받지 아니한다.\n</p>\n\n<p>\n  위원은 탄핵 또는 금고 이상의 형의 선고에 의하지 아니하고는 파면되지 아니한다.\n  대통령은 국무회의의 의장이 되고, 국무총리는 부의장이 된다. 모든 국민은 헌법과\n  법률이 정한 법관에 의하여 법률에 의한 재판을 받을 권리를 가진다.\n</p>\n\n<p>\n  국회의원은 현행범인인 경우를 제외하고는 회기중 국회의 동의없이 체포 또는\n  구금되지 아니한다. 헌법재판소의 장은 국회의 동의를 얻어 재판관중에서 대통령이\n  임명한다.\n</p>\n\n<p>\n  국가는 지역간의 균형있는 발전을 위하여 지역경제를 육성할 의무를 진다. 제3항의\n  승인을 얻지 못한 때에는 그 처분 또는 명령은 그때부터 효력을 상실한다. 이 경우\n  그 명령에 의하여 개정 또는 폐지되었던 법률은 그 명령이 승인을 얻지 못한 때부터\n  당연히 효력을 회복한다.\n</p>\n\n<p>\n  모든 국민은 신체의 자유를 가진다. 누구든지 법률에 의하지 아니하고는\n  체포·구속·압수·수색 또는 심문을 받지 아니하며, 법률과 적법한 절차에 의하지\n  아니하고는 처벌·보안처분 또는 강제노역을 받지 아니한다.\n</p>",
  "standings": [
    {
      "user": {
        "id": 13,
        "username": "user10"
      },
      "score": 36,
      "totalPenalty": 720,
      "standing": 1
    },
    {
      "user": {
        "id": 12,
        "username": "user09"
      },
      "score": 33,
      "totalPenalty": 660,
      "standing": 2
    },
    {
      "user": {
        "id": 11,
        "username": "user08"
      },
      "score": 30,
      "totalPenalty": 600,
      "standing": 3
    },
    {
      "user": {
        "id": 10,
        "username": "user07"
      },
      "score": 27,
      "totalPenalty": 540,
      "standing": 4
    },
    {
      "user": {
        "id": 9,
        "username": "user06"
      },
      "score": 24,
      "totalPenalty": 480,
      "standing": 5
    },
    {
      "user": {
        "id": 8,
        "username": "user05"
      },
      "score": 21,
      "totalPenalty": 420,
      "standing": 6
    },
    {
      "user": {
        "id": 7,
        "username": "user04"
      },
      "score": 18,
      "totalPenalty": 360,
      "standing": 7
    },
    {
      "user": {
        "id": 6,
        "username": "user03"
      },
      "score": 15,
      "totalPenalty": 300,
      "standing": 8
    },
    {
      "user": {
        "id": 5,
        "username": "user02"
      },
      "score": 12,
      "totalPenalty": 240,
      "standing": 9
    },
    {
      "user": {
        "id": 4,
        "username": "user01"
      },
      "score": 9,
      "totalPenalty": 180,
      "standing": 10
    },
    {
      "user": {
        "id": 1,
        "username": "super"
      },
      "score": 3,
      "totalPenalty": 0,
      "standing": 11
    },
    {
      "user": {
        "id": 2,
        "username": "admin"
      },
      "score": 3,
      "totalPenalty": 60,
      "standing": 12
    },
    {
      "user": {
        "id": 3,
        "username": "manager"
      },
      "score": 3,
      "totalPenalty": 120,
      "standing": 13
    }
  ],
  "canRegister": false
}
```
`"canRegister": false`를 확인할 수 있습니다.  

### Additional context

원래는 controller에 `@AuthNotNeededIfOpenSpace()`가 있었는데, 기능 구현하면서 일단은 commented out 해 놨습니다. 
위에 주석으로 FIX ME도 달아 놨으니 보고 이상하다 싶으면, 말씀주세요!

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2024-02-07 04:58 UTC, Jaehyeon1020 commented
PR 제목 수정 부탁드려요!!

2024-02-07 08:58 UTC, SH9480P commented on backend/apps/client/src/contest/contest.controller.ts
> +  // @AuthNotNeededIfOpenSpace()
해당 Use Case에 대한 새로운 커스텀 데코레이터가 필요할 듯 합니다.

@AuthNotNeededIfOpenSpace
groupId 1번이고 authNotNeeded면 통과
-> jwt가 전달되어도 auth 자체를 수행하지 않기 때문에  req.user가 존재할 수 없음, req.user.id는 항상 undefined

@DoNotCareIfAuthFailed
 -> auth를 시도하되, 실패해도 exception을 던지지 않음. req.user가 존재할 수도, 없을 수도 있음

jwt auth guard에 handlerequest에서 query string의 groupId에 접근도 가능하고, err랑 info로 에러처리가 가능하던데, 이런 식으로 구현하면 좋을 것 같아요

@DoNotCareInfAuthFailed의 이름은 임의로 정한거라 더 좋은 이름 생각나시면 rename도 좋습니다

2024-02-07 09:04 UTC, Jaehyeon1020 requested changes

2024-02-07 09:04 UTC, Jaehyeon1020 commented on backend/apps/client/src/contest/contest.service.ts
> +    // if user is not logged in, canRegister is always true
처음 canRegister가 false로 지정되어, userId가 없는 경우 true가 아닌 false가 설정될 것 같습니다. 수정 부탁드려요!

2024-02-07 16:29 UTC, SH9480P commented on backend/apps/client/src/contest/contest.controller.ts
> +  // @AuthNotNeededIfOpenSpace()
미팅 끝나기 전에 급하게 작성하여 설명이 부족한 듯 싶어 추가 코멘트 답니다

AuthNotNeededIfOpenSpace가 달려있으면 groupId가 1일 때에 한하여 무조건적으로 JWT validation 과정을 무시합니다.
그러나 여기에 필요한 use-case는 groupId가 1일 때에 한하여 JWT가 header에 포함되어있으면 validation을 수행하고, 없으면 수행하지 않는 상황이잖아요?
그래서 @AuthNotCareWhenFailedIfOpenSpace 같은 커스텀 데코레이터로 메타데이터를 전달하고, AuthGuard의 handleRequest에서 로그인에 실패했을 때 발생되는 error를 잡아 무시하는 전략을 취하면 어떨까 생각해 보았습니다.

다음 코드는 제가 작성했는데, 이해를 돕기 위한 예시로 대충 작성하여 정상적으로 동작하는지는 확인하지 않았습니다

```typescript
@Injectable()
export class JwtAuthGuard extends AuthGuard('jwt') {
  constructor(private reflector: Reflector) {
    super()
  }

  canActivate(context: ExecutionContext) {
    const request = this.getRequest(context)
    const isAuthNotNeeded = this.reflector.getAllAndOverride<boolean>(
      AUTH_NOT_NEEDED_KEY,
      [context.getHandler(), context.getClass()]
    )
    if (
      isAuthNotNeeded &&
      (!request.query.groupId || request.query.groupId === '1')
    ) {
      return true
    }
    return super.canActivate(context)
  }

  getRequest(context: ExecutionContext) {
    if (context.getType<GqlContextType>() === 'graphql') {
      return GqlExecutionContext.create(context).getContext().req
    }
    return super.getRequest(context)
  }

  handleRequest(err, user, info, context: ExecutionContext) {
    const request = this.getRequest(context)
    const groupId = +request.query.groupId ?? OPEN_SPACE_ID
    const authNotCare = this.reflector.getAllAndOverride<boolean>(
      AUTH_NOT_CARE_KEY,
      [context.getHandler(), context.getClass()]
    )
    if (authNotCare && info && groupId === OPEN_SPACE_ID) {
      return null
    }
    if (err || !user) {
      throw err || new UnauthorizedException()
    }
    return user
  }
}
```
이러면 @AuthNotCareWhenFailedIfOpenSpace 데코레이터가 달린 컨트롤러에 들어오는 요청은 groupId가 1일 때 로그인을 하지 않아도 req.user가 null이 되어 req.user?.id를 undefined로 받을 수 있을 것 같습니다

2024-02-09 14:35 UTC, gyunseo commented
@SH9480P 말씀하신 대로 로그인하지 않은 유저의 경우 Open Space에만 접근 가능하게 했습니다.
@Jaehyeon1020 일단은 로그인하지 않은 유저의 경우는 `canRegister: false`로 하게 하여, `Contest`에 가입하지 못하게 했습니다.
변경 사항 반영하여 커밋했습니다!

2024-02-11 16:45 UTC, SH9480P requested changes

2024-02-11 16:45 UTC, SH9480P commented on backend/libs/auth/src/jwt/jwt-auth.guard.ts
> +  }
groupId가 undefined일 때나 '0'일 때를 처리하지 못하네요
다음과 같이 바꿔주면 될 것 같아요

```typescript

  handleRequest(err, user, info, context: ExecutionContext) {
    const request = this.getRequest(context)
    const groupId = request.query.groupId ?? `${OPEN_SPACE_ID}`
    const authNotCare = this.reflector.getAllAndOverride<boolean>(
      DO_NOT_CARE_AUTH,
      [context.getHandler(), context.getClass()]
    )
    if (authNotCare && info && groupId === `${OPEN_SPACE_ID}`) {
      return null
    }
    if (err || !user) {
      throw err || new UnauthorizedException()
    }
    return user
  }

```

2024-02-11 16:45 UTC, SH9480P commented on backend/libs/auth/src/guard.decorator.ts
> +  SetMetadata(DO_NOT_CARE_AUTH, true)
AuthNotNeededIfOpenSpace랑 헷갈릴 것 같기도 하고...
다른 좋은 이름 없을까요
`SetUserNullWhenAuthFailedIfOpenSpace` ??

마땅히 없으면 DoNotCareAuthIfOpenSpace로 가시죠

2024-02-11 16:45 UTC, SH9480P commented on backend/apps/client/src/contest/contest.controller.ts
> +      return await this.contestService.getContest(id, groupId, req?.user?.id)
req 뒤에도 ?를 붙여야 하나요?

2024-02-11 16:45 UTC, SH9480P commented on backend/apps/client/src/contest/contest.controller.ts
> +      throw new InternalServerErrorException(error.message)
에러 로그를 찍게 해 놨으니 500에러에 메세지를 포함시킬 필요는 없을 것 같아요

2024-02-11 16:45 UTC, SH9480P commented on backend/apps/client/src/contest/contest.service.spec.ts
> +      await expect(
await 삭제

2024-02-11 16:45 UTC, SH9480P commented on collection/client/Contest/Get contest by ID/[401] Unauthorized.bru
불필요한 파일 같습니다

2024-02-12 14:14 UTC, gyunseo commented on backend/libs/auth/src/guard.decorator.ts
> +  SetMetadata(DO_NOT_CARE_AUTH, true)
헷갈리는 거 같아서, 제안해 주신 `SetUserNullWhenAuthFailedIfOpenSpace` 좋은 거 같습니다.

2024-02-12 15:36 UTC, SH9480P requested changes

2024-02-12 15:36 UTC, SH9480P commented on backend/apps/client/src/contest/contest.service.spec.ts
> +      ).to.be.rejectedWith(EntityNotExistException)
rejectedWith를 사용할 땐 expect 앞에 await을 붙여야 합니다
await을 제거하고 EntityNotExistException 대신 다른 exception을 넣어도 테스트가 통과됩니다. 잘못된 테스트 케이스죠

2024-02-12 15:36 UTC, SH9480P commented on backend/apps/client/src/contest/contest.service.spec.ts
> +      )
rejectedWith를 사용할 땐 expect 앞에 await을 붙여야 합니다

2024-02-12 15:36 UTC, SH9480P commented on backend/apps/client/src/contest/contest.service.spec.ts
> +      )
rejectedWith를 사용할 땐 expect 앞에 await을 붙여야 합니다

2024-02-12 15:36 UTC, SH9480P commented on backend/apps/client/src/contest/contest.service.spec.ts
> +      )
rejectedWith를 사용할 땐 expect 앞에 await을 붙여야 합니다

2024-02-12 15:36 UTC, SH9480P commented on backend/apps/client/src/contest/contest.service.spec.ts
> +      )
rejectedWith를 사용할 땐 expect 앞에 await을 붙여야 합니다

2024-02-13 05:14 UTC, gyunseo commented on backend/apps/client/src/contest/contest.service.spec.ts
> +      ).to.be.rejectedWith(EntityNotExistException)
헉 그렇네요!

2024-02-13 05:54 UTC, SH9480P approved these changes

2024-02-13 06:01 UTC, merged