feat(fe): implement recover account modal
skkuding/codedang pull request #1526
Opened 2024-02-29 04:10 UTC by B0XERCAT

### Description
아이디 찾기 및 비밀번호 초기화 모달 구현했습니다.
signup 모달과 비슷하게 zustand를 사용했습니다.
![image](https://github.com/skkuding/codedang/assets/97675977/0d1a59bc-52aa-4fe1-976b-d29ae8a4c813)
![image](https://github.com/skkuding/codedang/assets/97675977/12c2d708-5aa0-4b7f-8c5c-9d6f33265405)
![image](https://github.com/skkuding/codedang/assets/97675977/2125b158-2529-4895-8335-ea276e7e25cc)

signup과 거의 유사하게 구현했는데
signup에서는 email-auth가 잘 받아와지는 반면,
여기서는 401 에러가 발생해서 해당 부분만 잘 해결하고 병합하겠습니다.

Closes #1402 

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-02-29 04:57 UTC, aintbe commented
401이 어느 시점에서 발생하나요??

2024-02-29 05:32 UTC, B0XERCAT commented
> 401이 어느 시점에서 발생하나요??

401은 최종적으로 newPassword를 patch할 때 발생합니다.
header의 email-auth가 전달이 안돼서 그런 것 같습니다.

재민님이 어제 caddyfile 수정해주셔서 signup에서의 email 인증은 잘 되는데
이상하게 여기서는 잘 안되는 거 같습니다.

2024-02-29 09:20 UTC, dotoleeoak approved these changes

2024-02-29 09:32 UTC, dotoleeoak requested changes

2024-02-29 09:32 UTC, dotoleeoak commented on frontend-client/components/auth/ResetPasswordEmailVerify.tsx
> +      >
이 부분에 `onClick` 핸들러 때문에 헤더 값 변경이 안되는 거 같아요

```suggestion
      <Button
        type="submit"
        className={cn('mb-8 mt-2 w-full', !emailVerified && 'bg-gray-400')}
        disabled={!emailVerified}
      >
```

2024-03-01 00:19 UTC, B0XERCAT commented on frontend-client/components/auth/ResetPasswordEmailVerify.tsx
> +      >
onClick 제거하니까 정상 작동합니다! 감사합니다

2024-03-07 12:16 UTC, dotoleeoak approved these changes

2024-03-11 05:17 UTC, merged