fix(be): integrate problem exposeTIme isVisible
skkuding/codedang pull request #1673
Opened 2024-05-06 11:27 UTC by cho-to

### Description

(현재 진행중입니다 🥹)

problem 필드에 존재하는 exposeTime, isVisible 필드에서 isVisible 필드를 제거하고 exposeTime 필드만을 살립니다.

- 기존에는 exposeTime, isVisible 필드가 모두 존재해서 이로 인해 발생하는 문제들이 조금 있었습니다.
  - 특정 문제가 대회에 속하게 되면서 exposeTime이 설정되었다고 해도 getProblems 에는 isVisible을 기준으로 받아오는 경우 등등

exposeTime, isVisible을 둘 다 살려놓기에는 로직을 짤 때 중복되는 부분이 많을 것 같아서 exposeTime만을 살려놓는게 놓을 것 같다고 생각했습니다..

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-05-12 00:18 UTC, Jaehyeon1020 commented
클로즈 이슈 달아주세요!

2024-05-29 16:38 UTC, cho-to commented on apps/backend/apps/admin/src/problem/model/problem.output.ts
> +}
백엔드단에서 exposeTime을 isVisible로 변환하기 위해 ProblemWithIsVisible이라는 objectType을 새로 선언했습니다~
exposeTime은 제외되고, isVisible을 추가하였습니다.
이때, isVisible은 true, false, null이 될 수 있으며 null은 만약 problem이 ongoing/upcoming Contest에 속해있을 시 반환됩니다!

2024-05-29 16:38 UTC, cho-to commented on apps/backend/prisma/seed.ts
> +
시드 데이터에 원래 ongoingContest에만 문제들이 속했는데, 3개는 ongoing, 3개는 finished, 나머지 하나는 전체공개로 수정했어요

2024-05-30 01:13 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/problem/model/problem.output.ts
> +}
머지하실 때 프론트엔드팀에 안내 한번 부탁드려요!

2024-05-30 01:25 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +    problems: Problem[] | Problem
큰 문제는 아니지만 여기서 타입을 배열과 단일 객체 모두 허용하면서 return type도 복잡해지고, 함수 내부에서도 배열인지 아닌지 검사를 하는 로직이 추가돼서 가독성이 좀 떨어질 수 있을 것 같은데 배열만 받도록 허용하고, JSdoc으로 단일 객체를 넘기는 경우에도 배열로 감싸서 넣어야된다는 정보를 명시해주는건 어떨까요?

2024-05-30 01:25 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +      ) ?? []
`?? []` 요 로직을 타는 경우가 있을까요? 일단 함수에 Problem들이 넘겨지면 이 로직을 탈 일은 없을 것 같은데 지워도 괜찮지 않을까요!

2024-05-30 08:30 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +                : exposeTime == maxDate
조금 더 보니 <, > 등 부등호 연산자는 문제없고, ==, ===, !== 등 같은지를 비교하는 연산에서 getTime() 메서드 등 추가적인 방법이 필요하다고 하네요.

2024-05-30 09:10 UTC, cho-to commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +      ) ?? []
아 저거 lint 때문에 추가하고 삭제하는거 깜박했습니다 고칠게요!

2024-05-30 10:51 UTC, cho-to commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +                : exposeTime == maxDate
감사합니다~! 고쳤어요
고치는 김에 중복되는 타입 정리하고, 변수 이름도 통일했습니다!

2024-05-30 12:28 UTC, cho-to commented on apps/backend/apps/admin/src/problem/mock/mock.ts
> +        exposeTime < new Date() ? true : exposeTime == maxDate ? false : null,
이것도 고치겠습니다아

2024-06-03 01:03 UTC, Jaehyeon1020 commented
@admin/contest.service.ts의 removeProblemsFromContest에서, contest에 import되었던 문제가 contest에서 삭제되는 경우 exposeTime을 어떻게 조정해야하는지 논의 필요

2024-07-22 05:26 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/contest/contest.service.ts
> +              problemId: problemId
짧게 `problemId`만 써주셔도 좋을 것 같아요

2024-07-25 12:52 UTC, Jaehyeon1020 requested changes

2024-07-25 12:52 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +              : false,
visibleLockTime < new Date() 라면 이미 끝난 대회를 의미하게 됩니다.
진행중인 대회임을 나타내기 위해서 등호 방향을 바꿔주세요!

2024-07-26 05:18 UTC, Jaehyeon1020 commented on apps/backend/apps/client/src/problem/mock/problem.mock.ts
> +    visibleLockTime: new Date('2000-01-01'),
공개된 문제에 대한 데이터라면 `visibleLockTime`을 `MIN_DATE`로 설정해도 좋을 것 같습니다!

2024-07-26 05:18 UTC, Jaehyeon1020 commented on apps/backend/apps/client/src/submission/submission.service.ts
>            lt: new Date()
공개된 문제에 제출하는 로직이라면 **`visibleLockTime === MIN_DATE`인**(공개된) problem 데이터를 찾는게 적절할 것 같습니다!

2024-07-26 05:31 UTC, Jaehyeon1020 commented on apps/backend/apps/client/src/submission/submission.service.ts
>      }
`problem.visibleLockTime.getTime() === (new Date()).getTime()`으로 problem이 공개된 상태인지 검사하는 로직이 적절할 것 같습니다!

2024-07-26 05:34 UTC, Jaehyeon1020 commented on apps/backend/apps/client/src/submission/submission.service.ts
>          }
여기도 위와 같이 MIN_DATE와 비교가 필요할 것 같습니다

2024-07-26 05:34 UTC, Jaehyeon1020 commented on apps/backend/apps/client/src/submission/submission.service.ts
>            }
위와 같습니다

2024-07-29 14:33 UTC, cho-to commented on apps/backend/apps/client/src/submission/submission.service.ts
>      }
`problem.visibleLockTime.getTime() !== MIN_DATE.getTime() // 공개된 problem이 아닐 때`
로 공개된 problem이 아닐 때, 에러를 반환하도록 수정하였습니다~!

2024-07-29 14:49 UTC, cho-to commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +              : false,
```
return {
        isVisible:
          visibleLockTime.getTime() === MIN_DATE.getTime()
            ? true
            : visibleLockTime < new Date() ||
                visibleLockTime.getTime() === MAX_DATE.getTime()
              ? false
              : null,
        ...data
      }
```

으로 로직 수정하였습니다 !

2024-08-01 10:26 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/contest/contest.service.ts
UpdateContest 수정이 필요할 것 같습니다.
Contest의 EndTime이 변경되었을 때 그에 따라 딸려있는 문제들의 visibleLockTime들도 같이 변경이 필요해 보여요!

2024-08-01 10:40 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/contest/contest.service.ts
+ deleteContest ..

2024-08-01 10:46 UTC, Jaehyeon1020 requested changes

2024-08-01 10:46 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +  }
visibleLockTime < new Date()인 경우 visibleLockTime이 이미 지났으므로 isVisible 값을 조정이 가능한 상태, 즉 null이 되어야 할 것 같습니다. 반대로 visibleLockTime > new Date() 일 때 아직 visibleLockTime에 현재 시각이 도달하지 않았으므로 false가 되는게 맞을 것 같아요!

그래서 이부분 **visibleLockTime > new Date()**으로 변경이 필요해 보입니다!

2024-08-07 14:59 UTC, cho-to commented on apps/backend/apps/admin/src/contest/contest.service.ts
수정하였습니다 ~!!

2024-08-09 02:56 UTC, Jaehyeon1020 requested changes

2024-08-09 02:56 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/contest/contest.service.ts
> +    }
이 부분과 관련된 것 같은데 ... 문제가 특정 Contest에 import되어있는 상황에서 그 Contest의 endTime을 원래보다 작게 설정하면 (예를 들어 원래 2030-01-01이던걸 2024-12-01로 수정하는 경우) import되어있는 문제의 visibleLockTime이 그대로 2030-01-01로 남아있는 문제가 있습니다.

Update Contest의 경우에도 update 하고 있는 Contest의 endTime이 변경되면 (변경한 endTime 포함) 모든 endTime 중 가장 늦은 값으로 변경하는 로직의 추가가 필요해 보입니다.

2024-08-09 02:56 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +    }
이 부분 조건의 문제인 것 같은데, visibleLockTime이 MAX_DATE인 문제의 isVisible 변경이 불가능합니다. (false => true 불가, 반대로는 가능합니다) problem.visibleLockTime이 MAX이면 if문 내부 로직을 타지 않게 처리해줘야 할 것 같아요..!

2024-08-15 11:01 UTC, cho-to commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +    }
버그 찾아주셔서 감사합니다..........!!

2024-08-15 11:51 UTC, Jaehyeon1020 approved these changes
세달만에 머지.. 수고많으셨습니다!!

2024-08-18 06:00 UTC, jimin9038 commented
@cho-to 머지해두 되나요 ?

2024-08-18 12:38 UTC, merged