feat(be): add student-id and major field
skkuding/codedang pull request #1806
Opened 2024-07-11 09:35 UTC by hwantae

### Description

회원가입 시 원전공과 학번을 입력하는 필드를 만들었습니다.
### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-07-11 10:09 UTC, Jaehyeon1020 requested changes
추가로, prisma migrate를 실행한 후 migration 파일을 같이 커밋해주세요.

2024-07-11 10:09 UTC, Jaehyeon1020 commented on apps/backend/prisma/schema.prisma
> +  studentID  String    @unique
@map()을 이용해서 필드를 생성해주세요! (createTime, updateTime 필드 참고)

2024-07-11 10:09 UTC, Jaehyeon1020 commented on apps/backend/apps/client/src/user/user.service.ts
> +      major: 'defaultMajor'
'defaultStudentID', 'defaultMajor' 값이 아닌 socialSignUpDto를 통해 전달되는 값을 사용해주세요!

2024-07-22 07:28 UTC, gyunseo requested changes

2024-07-22 07:28 UTC, gyunseo commented on apps/backend/apps/client/src/user/user.service.ts
> +    // const { email } = await this.verifyJwtFromRequestHeader(req)
commented out 된 부분은 삭제하고 커밋해 주세요!

2024-07-22 07:28 UTC, gyunseo commented on apps/backend/apps/client/src/user/user.service.ts
> +    //await this.deletePinFromCache(emailAuthenticationPinCacheKey(email))
여기도요

2024-07-22 08:00 UTC, Jaehyeon1020 requested changes

2024-07-22 08:26 UTC, gyunseo approved these changes

2024-07-22 14:46 UTC, dayongkr commented
CI 테스트를 위해 브랜치 머지 해봤습니다!

2024-07-25 09:54 UTC, Jaehyeon1020 commented on apps/backend/prisma/schema.prisma
> +  major      String?
```
  studentID  String?   @unique @default("0000000000") @map("student_id")
  major      String?   @default("None")
```

기본값 세팅

2024-07-28 03:51 UTC, Jaehyeon1020 reviewed
FE 통합과 함께 머지 예정

2024-08-01 10:07 UTC, Jaehyeon1020 approved these changes
첫 커밋 수고하셨습니다!!

2024-08-01 10:10 UTC, merged