feat(fe): add editor copy paste preventing
skkuding/codedang pull request #1874
Opened 2024-07-25 16:46 UTC by jwoojin9

### Description

Contest의 enableCopyPaste 값이 true일 경우 코드에디터에서의 복사, 잘라내기, 붙여넣기를 막음

close #1783

### Additional context

Contest가 아닐 때 default 값은 일단 false로 설정했습니다.

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-07-26 05:45 UTC, jihorobert requested changes
enableCopyPaste가 true일때 복붙기능을 허용하고, false일때 기능을 막아놔야할 것 같아요!!

2024-07-26 05:49 UTC, jihorobert commented
말그대로 'enable' 이므로 false일 경우 복붙기능을 막는 것이 맞을 것 같아요!

2024-07-26 06:19 UTC, jwoojin9 commented
> 말그대로 'enable' 이므로 false일 경우 복붙기능을 막는 것이 맞을 것 같아요!

아! Contest들 값이 다 true이길래 테스트할려고 true일 때 막아놨다가 안 바꿔놨네요 ㅋㅋ

2024-07-26 06:22 UTC, jihorobert commented
> > 말그대로 'enable' 이므로 false일 경우 복붙기능을 막는 것이 맞을 것 같아요!
> 
> 아! Contest들 값이 다 true이길래 테스트할려고 true일 때 막아놨다가 안 바꿔놨네요 ㅋㅋ

좋습니다~ PR Description 파트도 false일경우 복붙기능 막는다고 설명 수정해주시면 좋을 것 같아요ㅎㅎ

2024-07-29 06:57 UTC, jwoojin9 commented on apps/frontend/components/CodeEditor.tsx
> +          !enableCopyPaste ? [copyPasteHandler()] : []
더 좋아보이네요 바꾸겠습니다!

2024-07-29 07:08 UTC, merged