feat(fe): redesign problem editor
skkuding/codedang pull request #1964
Opened 2024-08-17 05:13 UTC by youznn

### Description

problem editor 페이지의 수정 사항들을 헤더 위주로 리디자인 하였습니다.
기존 problem editor의 layout을 컴포넌트로 바꾸었습니다.
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/53b0a78c-0cfd-458b-a677-5e085939f376">

#TAS-521이 완료된다면, 유저 auth 패널 dropdown에 settings도 추가할 예정입니다.

close #TAS-712

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-08-17 08:42 UTC, jwoojin9 requested changes

2024-08-17 08:42 UTC, jwoojin9 commented on apps/frontend/components/auth/HeaderAuthPanel.tsx
> +                      ? 'text-white focus:rounded-none focus:bg-[#222939] focus:text-white'
focus:rounded-none에서 focus:를 없애고 rounded-none만 남겨야 할 것 같아요! focus:를 주니까 hover한 직후에 둥근 잔상이 아주 잠깐 보여요! 밑에 Logout도요..!

2024-08-17 09:02 UTC, jwoojin9 approved these changes
너무 수고하셨어요!!


사실 "focus:rounded-none에서 focus:를 없애고 rounded-none만 남겨야 할 것 같아요! focus:를 주니까 hover한 직후에 둥근 잔상이 아주 잠깐 보여요! 밑에 Logout도요..!"라고 달았었다가 귀찮으실 것 같아서 브랜치 들어간 김에 직접 수정했습니닿ㅎㅎ...

2024-08-17 09:06 UTC, youznn commented
> 너무 수고하셨어요!!
> 
> (사실 "focus:rounded-none에서 focus:를 없애고 rounded-none만 남겨야 할 것 같아요! focus:를 주니까 hover한 직후에 둥근 잔상이 아주 잠깐 보여요! 밑에 Logout도요..!"라고 달았었다가 귀찮으실 것 같아서 브랜치 들어간 김에 직접 수정했습니닿ㅎㅎ...)

헉 감사합니다!!  다시 보니 아직 수정 사항이 많아서 천천히 머지할게요~!! 😂

2024-08-17 09:09 UTC, dayongkr commented
리뷰어 수 진짜 많다😮

2024-08-17 09:12 UTC, youznn commented
> 리뷰어 수 진짜 많다😮

ㅋㅋㅋㅋㅋㅋㅋㅋ 고민하다가 전부 다 언급해버렸어요... 🙃

2024-08-17 09:31 UTC, dayongkr commented
> > 리뷰어 수 진짜 많다😮
> 
> 
> 
> ㅋㅋㅋㅋㅋㅋㅋㅋ 고민하다가 전부 다 언급해버렸어요... 🙃 

ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 사람 많은 프론트 팀👍👍

2024-08-21 09:26 UTC, B0XERCAT approved these changes
고생하셨습니다! 프론트 빌드 에러만 해결하고 머지하시면 될 것 같아요~

2024-08-22 04:42 UTC, merged