feat(be): implement group admin api
skkuding/codedang pull request #198
Opened 2022-08-13 15:49 UTC by aintbe

### Description

> Resolves #170
- group CRUD API
- group member 관리(추가, 가입 승인/거부, 추방, manager로 변경)
- group manager 관리(추가, 추방, 일반 member로 변경)

### Additional context

- group 생성 시에는 argon2의 해시 함수를 활용하여 초대 코드가 자동으로 발급됩니다.
  + 이 정도로 긴 코드가 필요할까요?
- group manager 관리 권한은 group admin에게만 부여해야 하지 않을까요?
  + 목적: group manager여도 Role이 일반 user라면 group manager 관리가 불가능하도록
  + 이 경우 group guard 및 role 관련 api를 서비스단에서 사용할 수 있도록 추가 구현이 필요합니다.
- deprecated group id 확정이 필요합니다.
  + 실존하는 그룹이 아니라는 점에서 가능하다면 0번인 게 좋을 것 같은데, 어떻게 생각하시나요?

:checkered_flag:  테스트 코드는 현재 작성 중입니다.

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-08-18 01:01 UTC, cranemont commented
1. 초대 코드는 hash보다는 그냥 간단하게 랜덤으로 8자리정도의 string 만들어서 사용하는건 어떨까요?. 변경이 가능한 부분이기도 하고, 복붙이 불가능한 경우도 있을거라서 너무 길면 불편할 것 같아서요!
2. 기획 단계에서도 해당 부분을 고민했었는데, group manager는 group admin이 직접 검증된 소수의 user에게 부여하는 것이라고 생각해서 그룹 삭제, 생성을 제외한 모든 권한을 넘겨줘도 괜찮다고 생각했어요..!
3. 0번 좋아요~~

2022-08-19 08:59 UTC, SH9480P commented
비밀번호 재설정이랑 회원가입 로직에서는 랜덤한 숫자 6자리를 PIN 번호로 사용하게끔 구현합니다! 참고하시라고 말씀드려요~

2022-08-23 13:22 UTC, SH9480P requested changes

2022-08-23 13:22 UTC, SH9480P commented on backend/src/group/group-admin.controller.ts
> +    } catch (error) {
`this.groupService.deleteMember`가 되어야 될 것 같네요

2022-08-23 13:22 UTC, SH9480P commented on backend/src/group/group.service.ts
> +  }
Promise.all(members)을 반환하게 하면 `await this.prisma.user.findUnique`랑 `await this.prisma.userGroup.create` 둘 다 병렬적으로 처리되는 건가요??

2022-08-23 13:22 UTC, SH9480P commented on backend/src/group/group-admin.controller.ts
> +  }
offset에 왜 -1이 추가되나요??

2022-08-23 13:40 UTC, SH9480P commented
지난번 회의에서 request parameter 표기법을 camelCase로 통일하기로 결정했습니다!

2022-08-24 07:03 UTC, aintbe commented
> 지난번 회의에서 request parameter 표기법을 camelCase로 통일하기로 결정했습니다!

```ts
@Param('group_id', ParseIntPipe) groupId: number
```
현재 이런 식으로 파라미터를 받아오고 있는데, 프론트에서 넘겨주는 것도 camelCase로 통일된 것인가요??

2022-08-24 07:06 UTC, aintbe commented on backend/src/group/group-admin.controller.ts
> +  }
프리즈마 API는 특정 레코드부터 여러 레코드를 한꺼번에 가져올 때, skip할 레코드의 개수를 받습니다. (e.g., 첫번째 레코드부터 가져올 경우 0개 skip) 프론트에서 넘겨주는 offset은 현재 글 혹은 글 목록의 인덱스이기 때문에, offset-1 (컨트롤러) = skip (서비스)로 전달되는 방식입니다!

2022-08-24 07:14 UTC, aintbe commented on backend/src/group/group.service.ts
> +  }
(findUnique -> create) 묶음이 멤버별로 병렬적으로 이루어지는 것을 의도했는데, 다시 생각해보니 map 메소드가 순서대로 처리해서 완전한 병렬은 안 될 것 같네요ㅠㅠ 대신에
```ts
return await this.prisma.userGroup.create({
```
에서 await을 삭제해서 create에 한해 병렬적으로 처리할 수 있도록 수정했습니다. 시퀀스는 findUnique -> create (기다림 X) -> findUnique -> ... 가 되겠네요!

2022-08-24 07:14 UTC, aintbe commented on backend/src/group/group-admin.controller.ts
> +    } catch (error) {
수정했습니다~

2022-08-24 07:16 UTC, aintbe commented on backend/src/group/group-admin.controller.ts
> +@UseGuards(RolesGuard)
https://github.com/skkuding/next/pull/131#issue-1306313013 여기서 저는 Roles 데코레이터가 필요 role을 지정해주는 역할을 수행하고, 실제로 가드를 사용하기 위해서는 UseGuard를 써야한다고 이해했는데, 아닌가요?

2022-08-24 07:28 UTC, aintbe commented
## 수정 사항 정리
- 초대 코드 문제
  + 피그마에 따르면 "그룹 페이지 접속 -> 적절한 초대 코드 입력 -> 가입"이 아니라 초대 코드를 입력해야 그룹의 존재를 확인할 수 있는 구조여서, 초대 코드가 그룹별로 겹치면 안 될 것 같아 hash를 사용했었습니다!
  + 다만 복사 후 붙여넣기가 불가능할 경우를 고려하여, base64의 8자리 string을 만드는 것으로 대체했습니다!
- DEPRECATED group id
  + 0으로 고정되었습니다.
- group manager
  + role과 관계없이 group member와 관련된 모든 권한을 부여받습니다.

2022-08-24 10:38 UTC, SH9480P commented
> > 지난번 회의에서 request parameter 표기법을 camelCase로 통일하기로 결정했습니다!
> 
> ```ts
> @Param('group_id', ParseIntPipe) groupId: number
> ```
> 
> 현재 이런 식으로 파라미터를 받아오고 있는데, 프론트에서 넘겨주는 것도 camelCase로 통일된 것인가요??

#207 에 구현된 걸 보면 그런 것 같네요

2022-08-24 14:15 UTC, cho-to commented on backend/src/group/group.service.ts
> +    })
궁금한 점이 있는데, 여기서 `UserGroup.length` 를 하게 되면 `is_registered` 값이 false 인 userGroup 들도 고려해서 length가 return 되나요??

2022-08-25 11:20 UTC, aintbe commented on backend/src/group/group.service.ts
> +    })
그렇네요!!! 승인된 멤버만 세도록 수정했습니다!

2022-08-26 12:50 UTC, SH9480P commented on backend/src/group/group-admin.controller.ts
> +@UseGuards(RolesGuard)
Roles 데코레이터는 필요 role을 지정해주고, request user객체에 담긴 id로 사용자의 role을 가져와서 필요 role보다 권한이 높은지 검사하는 일까지 수행합니다
Roles 데코레이터를 사용하지 않고 RolesGuard만 사용하면 필요 role를 기본값으로 User로 설정하게 되어있네요

2022-08-29 06:45 UTC, SH9480P requested changes

2022-08-29 06:45 UTC, SH9480P commented on backend/src/group/group.service.ts
> +      ).id
findUnique에 rejectOnNotFound옵션 주는게 필요하지 않을까요?
그리고 student_id필드가 null인 사용자를 추가하고자 할 때 어떤 일이 생기는지 궁금합니다

2022-08-29 06:45 UTC, SH9480P commented on backend/src/group/group.service.ts
> +  }
controller에서 createMembers 함수 호출할 때에도 앞에 await을 붙여줄 텐데, return할 때 await을 붙여줘야하나요?

2022-08-29 06:45 UTC, SH9480P commented on backend/src/group/group-admin.controller.ts
> +    } catch (error) {
수정이 안되었네요

2022-09-02 13:39 UTC, aintbe commented on backend/src/group/group-admin.controller.ts
> +  } // TODO: 사용자로 UserGroup 생성
`createGroup`은 서비스단에서 고의로 발생시키는 예외가 없어서, 만일 예외가 발생한다면 시스템 자체의 예외일 거고 이건 nest의 global exception handler가 처리해줄 테니 굳이 작성할 필요가 없다고 생각했습니다!

2022-09-02 13:45 UTC, aintbe commented on backend/src/group/group-admin.controller.ts
> +    } catch (error) {
이번엔 진짜 수정했습니다!!!

2022-09-02 13:46 UTC, aintbe commented on backend/src/group/group.service.ts
> +  }
아까 얘기한 대로 use case를 바꾸어서 해당 코드를 안 쓰게 되었는데, 저대로 사용했다면 안 써도 될 것 같아요!

2023-01-11 06:41 UTC, SH9480P commented
본 PR은 잠시 pending하겠습니다. GraphQL 적용 후에 변경 예정입니다.

2023-06-22 13:10 UTC, aintbe commented
마지막 커밋 이후로 main 브랜치에서 분기가 많이 된 점, 다른 PR과 개발 내용이 겹치는 점 등을 고려하여 새로 PR을 올려 개발하고 본 PR은 close합니다.

2023-06-22 13:10 UTC, closed without merging