feat(fe): add english major name
skkuding/codedang pull request #2023
Opened 2024-08-27 13:31 UTC by jwoojin9

### Description

영어 학과명을 추가하였고, signup 모달에서 튀어나올 시 '...'처리하도록 하였습니다!

closes TAS-781

하나하나 대학별로 공홈 들어가서 영어명 확인했으니 아마 다 정확할 겁니다..! 다만 글융의 '자기설계융합전공'은 정말 정보가 하나도 없는 것 같아 임의로 번역했습니다..!

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-08-27 13:34 UTC, jimin9038 requested changes

2024-08-27 13:34 UTC, jimin9038 commented on apps/frontend/lib/constants.ts
> -  '학과 정보 없음',
'none'으로 바꿔주세요 (백엔드 디폴트 값 none 이라서 프론트랑 일치하는 게 좋을 것 같아요

2024-08-27 13:35 UTC, jwoojin9 commented on apps/frontend/lib/constants.ts
> -  '학과 정보 없음',
근데 실제 유저한테는 none으로 보이면 안 되지 않나요?

2024-08-27 13:36 UTC, jwoojin9 commented on apps/frontend/lib/constants.ts
> -  '학과 정보 없음',
none을 추가하고 none일 때 Department Info...를 보여줄까요?

2024-08-27 13:46 UTC, jwoojin9 commented
@jihorobert 충돌날까봐 settings는 안 건드렸는데 signup 모달에서 학과가 'none'일 때 'Department Information Unavailable / 학과 정보 없음' 보여주도록 구현했으니까 참고해서 변경해주세요!!

2024-08-27 14:31 UTC, jimin9038 commented on apps/frontend/lib/constants.ts
> -  '학과 정보 없음',
좋습니다~!!

2024-08-28 04:26 UTC, B0XERCAT commented on apps/frontend/components/auth/SignUpRegister.tsx
> +                  {!majorValue ? 'First Major' : majorValue}
majorValue ?? 'First Major' 로 수정할 수 있을 것 같아요!

2024-08-29 12:58 UTC, B0XERCAT approved these changes
고생하셨습니다!

2024-08-30 03:21 UTC, jimin9038 approved these changes

2024-08-30 03:26 UTC, merged