feat(be): forbid score update when submit exists
skkuding/codedang pull request #2051
Opened 2024-08-31 07:03 UTC by Jaehyeon1020

### Description

Closes TAS-787

Submit이 존재하는 경우 testcase를 업데이트 할 수 없도록 하고, Contest의 경우 문제를 import, delete할 수 없도록 변경합니다.

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2024-09-02 06:10 UTC, jimin9038 requested changes

2024-09-02 06:10 UTC, jimin9038 commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +    const submissions = await this.prisma.submission.findMany({
`const submission = await this prisma.submission.findFirst`
로 하고 !submission 검사하는 것이 좋을 것 같아요

2024-09-02 06:10 UTC, jimin9038 commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +    if (submissions.length && testcases?.length) {
이렇게 되면 submission은 있음에도, 문제의 `testcases`를 다 지워버렸을 때는(`testcases === []`일 때) update가 되어버릴 것 같아요. 제출이 하나라도 있으면 테스트케이스를 아예 고칠 수 없게 해야하므로 `testcases` 가 `null`인지(update 대상인지) 검사해야 할 것 같아요.

2024-09-02 09:29 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/problem/problem.service.ts
> +    if (submissions.length && testcases?.length) {
모두 반영했습니다~!

2024-09-03 07:22 UTC, jimin9038 approved these changes
👍

2024-09-03 07:54 UTC, merged