refactor(be): use global exception filter to admin contest and admin group modules
skkuding/codedang pull request #2099
Opened 2024-09-19 10:06 UTC by Jaehyeon1020

### Description

Closes TAS-911

Admin Contest 모듈과 Group 모듈이 Global Exception Filter를 제대로 사용하도록 리팩토링합니다.

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-09-19 10:57 UTC, mnseok requested changes
코멘트 남겨둔거 하나만 확인해주시면 될 것 같아요

2024-09-19 10:57 UTC, mnseok commented on apps/backend/apps/admin/src/contest/contest.service.ts
> +        } catch {
여기서 발생한 오류 그냥 넘겨도 되나요?
그리고 아래쪽에 prisma update 부분 에러처리 안되있는것같아요

2024-09-19 14:21 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/contest/contest.service.ts
> +        } catch {
넵 update 실패 시 그냥 포함시키지 않는 로직입니다!

prisma update 에러처리는 빠뜨렸는데 추가했어요~

2024-09-19 15:35 UTC, mnseok approved these changes
굿굿

2024-09-20 04:04 UTC, Jaehyeon1020 commented
브랜치 전략 변경 후 머지 예정

2024-09-26 09:14 UTC, jimin9038 commented
coolify 배포를 위해서 닫았다가 열게요.

2024-10-03 13:46 UTC, merged