refactor(be): adm user cli auth exception refator
skkuding/codedang pull request #2115
Opened 2024-09-23 14:20 UTC by hwantae

### Description
Closes TAS-912
Admin User 모듈과 Client auth 모듈의 exception을 refactoring하였습니다.

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-09-24 04:24 UTC, Jaehyeon1020 requested changes

2024-09-24 04:24 UTC, Jaehyeon1020 commented on collection/admin/Contest/Get Contest User/Succeed.bru
잘못 올라온 것 같은데 지워주세요!

2024-09-24 04:24 UTC, Jaehyeon1020 commented on collection/admin/Contest/Get User and Score/Succeed.bru
이것도 잘못 올라온 것 같은데 지워주세요!

2024-09-26 09:11 UTC, jimin9038 commented
coolify 배포를 위해서 닫았다가 열게요.

2024-09-28 08:53 UTC, Jaehyeon1020 requested changes

2024-09-28 08:53 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/user/user.service.ts
>    }
userGroups는 findMany의 결과를 담고 있는 배열인데, findMany는 찾는 값이 없는 경우 [] (빈 배열)을 반환합니다.
그런데 javascript에서 빈 배열은 Truthy한 값(조건문 안에서 True로 평가되는 값)이기 때문에, if (userGroup)은 항상 True로 평가됩니다.
그래서 userGroup이 빈 배열인지를 검사하기 위해서는 if (userGroup.length > 0)으로 바꿔주셔야 의도하신 동작이 가능할 것 같아요.

그런데 위 내용과 별개로, 이 함수는 원래 코드를 봤을 때 findMany에서 빈 배열이 반환되면 그 결과를 에러로 간주하지 않고 그대로 다시 반환하는 함수였어서 userGroups가 빈 배열인 경우에 예외처리는 불필요할 것 같습니다. ㅠㅠ 고생해주셨지만 다시 원래의 코드로 돌리는 것이 맞을 것 같습니다..!

다른 의견 있으시면 알려주세요!

2024-09-28 08:53 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/user/user.service.ts
>      }
이 부분은 userGroup이 null인 경우 예외를 던지는 것이 맞을 것 같아요!
그런데 저희 프로젝트에서 전체적인 스타일이 값을 검사해서 없는 경우 예외를 던지고, 아래에서 리턴을 해주는 형식이라서, 맞춰서 한번 짜주시는건 어떨까요?

```
if (!userGroup) {
  throw ~~~
}

return ~~~
```

위와 같은 형식이면 좋을 것 같아요!

2024-09-28 08:53 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/user/user.service.ts
>      }
이부분은 예외 종류 변경해주신 이유가 있으실까요?
에러 코드가 바뀌게 되어서 여쭤봅니다!

2024-09-28 08:53 UTC, Jaehyeon1020 commented on apps/backend/apps/client/src/auth/auth.service.ts
> +import { Inject, Injectable, NotFoundException } from '@nestjs/common'
사용되지 않는 Exception은 지워주세요!

2024-09-28 08:53 UTC, Jaehyeon1020 commented on apps/backend/apps/client/src/auth/auth.service.ts
> +  EntityNotExistException,
여기도 사용되지 않는 Exception은 지워주세요!

2024-10-01 07:24 UTC, hwantae commented on apps/backend/apps/admin/src/user/user.service.ts
>      }
비즈니스 익셉션에 있는걸로 바꾸려고 한건데 에러코드가 바뀌게 된다면 원래대로 돌려놓겠습니다!

2024-11-08 03:19 UTC, Jaehyeon1020 reviewed
이 부분은 사소해서 제가 해결하고 머지할게요!

2024-11-08 03:19 UTC, Jaehyeon1020 commented on apps/backend/apps/admin/src/user/user.resolver.ts
>      }
이 부분도 없애주셔도 될 것 같아요! (InternalServerError도 Global Exception Filter에서 처리됩니다.)

2024-11-08 03:33 UTC, Jaehyeon1020 approved these changes

2024-11-08 03:33 UTC, merged