feat(be): implement group user api
skkuding/codedang pull request #295
Opened 2022-12-22 17:59 UTC by cho-to

### Description
> Resolves #178 

Group 페이지에서 Admin을 제외한, User 계층에서 필요한 API들을 구현합니다.
이와 관련해 자세한 메소드들은 #178 을 참조해주시면 감사하겠습니다.

큰 기능들은 아래와 같습니다.
- user의 group 조회 기능(public group/my group/group manager, member 조회 등)
- user의 group 가입 및 탈퇴 기능

### Additional context

아래 내용은 추후 구현되어야할 사항으로, 아직 구현이 되지 않았으나 수정해 이 PR에 지속적으로 진행사항 업로드하겠습니다.

- [ ] controller 부분 추가
- [ ] test 부분 추가
- [ ] 코드 정리 및 간결화

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-01-27 12:56 UTC, aintbe commented
Group API에서 기획이 변경되었습니다. #356 확인해주세요~ @cho-to @jspark2000

2023-02-03 11:42 UTC, aintbe commented
- `isRegistered` 필드 삭제 후 관련 코드에서 해당 필드의 언급을 삭제하였습니다. 이 필드는 무시하시고 작업하시면 됩니다.
- UserGroup 테이블의 PK(id)를 양수 값이 아닌 (userId, groupId)의 조합으로 변경하였습니다. UserGroup 레코드를 where문으로 검색하는 상황이 필요하다면 두 필드의 조합을 조건으로 제공하시면 됩니다. @cho-to @jspark2000

2023-02-08 13:18 UTC, SH9480P requested changes

2023-02-08 13:18 UTC, SH9480P commented on backend/src/group/group.service.ts
> +  }
- 프론트엔드에서 작업하기 좋게 `requireApprovalBeforeJoin` 여부에 따라 return값을 다르게 지정해주면 좋을 것 같아요. 예를 들면, 바로 가입되면 "가입되었습니다!"를 띄우거나 group 상세페이지로 redirect를 시켜줄 수 있고, 가입 승인이 필요하면 "가입 요청이 전달되었습니다!"를 띄울 수 있잖아요?
- 중복 가입요청 거절 예외처리는 존재하지만, 중복 가입 검사를 하는 예외처리는 없네요. 이미 가입된 사용자가 가입을 하려고 하면 `requireApprovalBeforeJoin` 여부와 상관없이 예외를 발생시키면 좋을 것 같아요.

2023-02-08 13:18 UTC, SH9480P commented on backend/src/group/group.controller.ts
> +      }
Controller에서 `PrismaClientKnownRequestError`를 잡아 404 error를 던지는 부분에 다른 방식을 조심스레 제안해봅니다.

저는 workbook api에서 update를 하거나 delete를 할 때 수정할 record가 없는 경우, service 메서드 안에 try-catch를 적용하여 에러가 발생했을 때 if (error instanceof PrismaClientKnownRequestError && error.code === 'P2025')인지를 검사하여 만일 맞다면 `EntityNotExistException`를 throw하고, 아니라면 해당 에러를 re-throw하는 식으로 구현했습니다. controller에서는 `EntityNotExistException`가 발생했는지만을 검사하고요.

그렇게 한 이유는, **record가 존재하지 않아** update와 delete에 실패했기 때문에 `EntityNotExistException`을 사용하는 것이 더 명시적인 방향이라고 생각했기 때문입니다.

로직보다는 스타일적인 부분에 더 가까운 것 같아요. assignee분들의 의견이 궁금합니다.
(controller error.code가 p2025인지 검사하는 부분은 꼭 필요하다고 생각합니다!)

delete를 하기 전에 findUnique로 delete할 레코드가 있는지 검사하는 방법도 있습니다! DB에서 동일한 연산을 반복하는 비효율이 있지만 코드가 깔끔해지긴 하죠. (개인적으로 좋아하는 방법은 아닙니다)

2023-02-10 03:53 UTC, SH9480P commented
group 전체를 받아오는 API에 pagination이 구현되어 있지 않네요! 
getGroups에만 cursor based pagination 구현 부탁드립니다

2023-02-10 05:53 UTC, cho-to commented on backend/src/group/group.controller.ts
> +      }
저도 error.code가 P2025인지 검사하고 EntitiyNotExistException으로 처리해주는게 더 나을 것 같습니다 :)

2023-02-10 06:03 UTC, cho-to commented on backend/src/group/group.service.ts
> +
GroupJoin Modal 띄울때 필요한 정보들을 반환하도록 구현했습니다! 
조금 더 명시적으로 `getGroupJoinModalById `로 표현해볼까요?

2023-02-10 06:06 UTC, cho-to commented on backend/src/group/group.service.ts
> +  }
넵 추가하였습니다~!

2023-02-10 06:07 UTC, cho-to commented on backend/src/group/group.service.ts
> +      .map((group) => {
넵! 반영해서 수정해보았습니다 !

2023-02-10 06:30 UTC, cho-to commented on backend/src/group/group.controller.ts
> +  }
GroupMemberGuard 추가해서 반영했습니다 :)

2023-02-10 20:27 UTC, cho-to commented on backend/src/group/group.service.ts
> +  }
- 바로 가입이 되었으면 create한 result에다가 `isJoined: true`를, 가입 승인이 필요할 시에는 `userId`, `groupId`와 함께 `isJoined: false`를 반환하도록 하였습니다!
- 일단은 db에 usergroup에 속해 있는지 한 번 더 검색하고 만약 있다면 `Group join record already exists`란 메세지를 반환하도록 했습니다. 한 번 더 db를 조회하는 것 대신`allowJoinFromSearch` 여부 및 그룹 존재 여부 때문에 그룹을 검색할때 `userGroup`을 반환하게 해 반환된 userGroup 으로도 그룹에 속해있는지 확인할 수 있을 것 같은데 어떤 방법이 좋을까요 🤔 ...

2023-02-12 19:56 UTC, cho-to commented on backend/src/group/group.service.ts
> +
`getGroupJoinById`를 따로 만들기보다는, 기존 getGroup을 이용해 통합하는게 나을 것 같다는 의견을 반영하여, 두 개를 getGroup으로 합쳐보았습니다.
 만약 사용자가 특정 그룹에 가입이 되어있지 않다면 가입modal에 필요한 정보들을 반환하고(초대 URL만으로 가입이 되는 그룹에도 modal창이 뜨는지 모르겠어서 일단 `allowJoinFromSearch`가 true인 group에 한해서 반환하게 설정하였습니다), 만약 가입이 되어있다면 group page에 필요한 정보(description, group name)만을 반환하도록 해보았습니다 ! 😀

2023-02-12 20:34 UTC, cho-to commented
> group 전체를 받아오는 API에 pagination이 구현되어 있지 않네요! getGroups에만 cursor based pagination 구현 부탁드립니다

cursor based pagination 구현해서 코드 업데이트하였습니다 😃 !

2023-02-14 03:55 UTC, SH9480P commented on backend/src/group/group.service.ts
> +  }
> 일단은 db에 usergroup에 속해 있는지 한 번 더 검색하고 만약 있다면 Group join record already exists란 메세지를 반환하도록 했습니다. 한 번 더 db를 조회하는 것 대신allowJoinFromSearch 여부 및 그룹 존재 여부 때문에 그룹을 검색할때 userGroup을 반환하게 해 반환된 userGroup 으로도 그룹에 속해있는지 확인할 수 있을 것 같은데 어떤 방법이 좋을까요 🤔 ...

Group modal 띄울 때 프론트엔드가 User가 Group에 가입되어있는지 알 수 있으니 db조회를 추가로 하지 않아도 되지 않느냔 말씀이신가요??
그래도 API가 달라서 검사를 해 줘야 하지 않을까요..?

2023-02-14 04:01 UTC, SH9480P approved these changes

2023-02-14 14:45 UTC, cho-to commented on backend/src/group/group.service.ts
> +  }
JoinGroupById 에서 기존 코드(user가 특정 그룹에 join 되었는지 db usergroup 에서 한 번 더 조회) 대신에
```
    const group = await this.prisma.group.findFirst({
      where: {
        id: groupId,
        config: {
          path: ['allowJoinFromSearch'],
          equals: true
        }
      },
      select: {
        config: true,
        userGroup: {
          select: {
            userId: true
          }
        }
      },
      rejectOnNotFound: () => new EntityNotExistException('group')
    })

    const isJoined = group.userGroup.includes({ userId: userId })
```
이렇게 db를 2번 조회하지 않고 한번에 받아올 수 있을 것 같다는 말이었는데 호옥시 이해되시나요...?

2023-02-14 15:56 UTC, SH9480P commented on backend/src/group/group.service.ts
> +  }
아하~~ 이해됩니다!!
한번에 받아오는 방법이 더 좋은 것 같은데요??
지윤님 하고싶으신 방법으로 하시면 될 것 같아요 👍

2023-02-19 15:50 UTC, merged