210 group
skkuding/codedang pull request #305
Opened 2022-12-29 07:56 UTC by kee711

### Description

close #210

1. GroupListSection
<img width="932" alt="스크린샷 2022-12-29 오후 4 46 50" src="https://user-images.githubusercontent.com/59683761/209919968-f4782f08-ea8d-4eec-85e5-8b97b732af17.png">

2. Group Notice Page
<img width="887" alt="스크린샷 2022-12-29 오후 4 55 01" src="https://user-images.githubusercontent.com/59683761/209920823-0b04631d-fa34-4467-8ab7-f601cdf95e86.png">

3. Group Contest Page
<img width="884" alt="스크린샷 2022-12-29 오후 4 55 15" src="https://user-images.githubusercontent.com/59683761/209920846-04dd49af-e859-47d4-98f1-da5283efd41a.png">

4. Group Workbook Page
<img width="921" alt="스크린샷 2022-12-29 오후 4 55 27" src="https://user-images.githubusercontent.com/59683761/209920861-9820d00b-f617-4eac-a82d-6c6ae53d1ddf.png">

5. Group Member Page
<img width="927" alt="스크린샷 2022-12-29 오후 4 55 38" src="https://user-images.githubusercontent.com/59683761/209920887-e3a411ad-0a33-472d-8e63-ce371993e912.png">

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-01-12 15:00 UTC, jimin9038 submitted a review, later dismissed

2023-01-12 16:22 UTC, goo314 commented on frontend/src/user/group/pages/index.vue
> +    <GroupListSection :group-list="myGroupList" title="My Group" />
이건 피그마쪽을 수정해야 했는데 까먹었네요. 

해당 부분은 원래 그룹을 관리하는 유저(leader)가 admin 페이지에 접근할 수 없어 setting 버튼을 만들었었는데, 현재는 leader가 admin 페이지 접근 가능하도록 결정했습니다(단, 그룹 생성 및 삭제 불가)

피그마 디자인 곧 수정할게요😃

2023-01-12 16:25 UTC, goo314 commented on frontend/src/user/group/components/GroupListSection.vue
> +  <Modal v-model="groupDescModalVisible" class="h-96 w-[600px]">
기존 브랜치의 모달 컴포넌트와 merge된 모달 컴포넌트 속성이 달라서 그렇습니다! named slot이 없어졌어요.

template tag 없애고 적당한 css 적용시키면 해결될 겁니다! 수정 부탁해요😊

2023-01-19 09:01 UTC, kee711 commented on frontend/src/user/group/components/Contest.vue
> +  id: number
추후 API 연동에 쓰입니다!

2023-01-25 08:46 UTC, kee711 commented on frontend/src/user/group/pages/index.vue
> +    <GroupListSection :group-list="myGroupList" title="My Group" />
이건 나중에 한다고 합니다 :)

2023-01-25 08:50 UTC, goo314 commented on frontend/src/user/group/components/GroupListSection.vue
> +      <Pagination v-model="currentPage" :number-of-pages="3" />
백엔드 쪽에서 한 페이지씩 받아올 예정이라 API 연결때 하면 될 것 같아요!

2023-02-20 07:19 UTC, goo314 requested changes

2023-02-20 07:19 UTC, goo314 commented on frontend/src/user/group/components/GroupListSection.vue
> +  myGroup: boolean
`myGroup` 보다는 `isMyGroup` 으로 변경해주면 좋을 것 같아요

2023-02-20 07:19 UTC, goo314 commented on frontend/src/user/group/pages/index.vue
> +    </Modal>
![image](https://user-images.githubusercontent.com/62930375/220036057-95017319-6929-40d6-b8c1-27758154cb4a.png)

초대 코드를 입력하는 글은 위로 가고 "group not found" 글씨가 제일 아래로 가면 좋을 것 같아요
살짝 바꿔봤는데 아래 사진처럼 ? 어떤가요 ??

![image](https://user-images.githubusercontent.com/62930375/220037231-3ed9985d-a192-449f-b582-f2bda5bc09c6.png)

2023-02-20 07:19 UTC, goo314 commented on frontend/src/user/group/pages/index.vue
> +          <Button class="py-2"><IconSendFilled /></Button>
`<IconSendFilled/>` 말고 이 아이콘은 어떤가요? 
회원가입 모달에 쓰는 아이콘이기도 하고 fa6-solid icon set이라 통일하면 좋을 것 같아요
수정하시면 package.json의 carbon 부분은 지워주세요 :)

![image](https://user-images.githubusercontent.com/62930375/220037963-ab97642c-7784-48ab-8b79-f38fafbfb02e.png)

2023-02-21 05:22 UTC, eunnbi commented on frontend/src/common/components/Atom/InputItem.vue
>  }>()
`required` 대신 `message`가 더 활용도가 높을 거 같아서 바꾼거예요! 지금 상황에서는 바꿀 필요가 없긴 하죠 ㅎㅎ 변경 전으로 수정해도 상관없습니다!

2023-02-21 06:49 UTC, goo314 approved these changes

2023-02-21 06:50 UTC, merged