feat(be): public contest get API
skkuding/codedang pull request #371
Opened 2023-02-04 07:24 UTC by Hyeongrok1

### Description
구현한 기능은 다음과 같습니다.

- ContestController 이름을 PublicContestController로 변경함

- 기존에 개발된 API는 사용자가 등록한 대회를 따로 구분하지 않고 대회 목록을 반환했음
     ---> 사용자가 로그인 된 경우 사용자가 등록된 대회를 구분하여 대회 목록을 반환하도록 수정

```
async getContests(user: AuthenticatedUser): Promise<{
    registeredOngoing?: Partial<Contest>[]
    registeredUpcoming?: Partial<Contest>[]
    ongoing: Partial<Contest>[]
    upcoming: Partial<Contest>[]
    finished: Partial<Contest>[]
  }>
```
- getModalContest method를 삭제했습니다.

- contestId를 통해 contest의 자세한 정보를 가져오는 getContest 메소드를 구현했습니다.

### Additional context

- ongoing, finished 대회들은 endTime이 작은 순서대로, upcoming 대회들은 startTime이 작은 순서대로 반환합니다.
- 만약 사용자가 로그인하지 않은 상태일 경우, req.user는 undefined가 되고 registered contests들을 반환하지 않습니다. 

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-02-10 06:30 UTC, aintbe requested changes

2023-02-10 06:30 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    })
변수명에 **Contests**가 들어가니까 다음처럼 할당하는 게 더 직관적일 것 같아요!
```ts
const registeredContests = (await this.prisma.user.findUnique({...})).contest
```

2023-02-10 06:30 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    const upcomingContest = contests.filter(
필터링 후에 정렬하는 게 로드가 적을 듯합니다!

2023-02-13 14:19 UTC, SH9480P commented on backend/src/contest/contest.service.ts
> +
`contestSelectionOption`에 의해 가져온 contests 객체가 Partial<Contest>라고 할 수 있나요??
Contest 모델에 포함되지 않는 group:{id, groupname}이 있기 때문에 Partial로 볼 수 없지 않나요..?
@aintbe @Hyeongrok1

2023-02-14 05:56 UTC, JungangHighschool commented on backend/src/contest/contest.service.ts
>    }
쿼리를 user와 contest에 대하여 각각 보내는 것 보다 contest 에만 보낸 후 그 결과값을 후처리하는 것은 어떤가요? 시간이 더 걸리려나요?

2023-02-14 10:20 UTC, Hyeongrok1 commented on backend/src/contest/contest.service.ts
>    }
처음에는 contest 쿼리만 작성하고 그 후에 user가 등록된 contest만 추려내는 식으로 하려고 했었지만 user가 등록한 contest를 알아내기 위해서 결국 user 쿼리를 작성해 등록된 contest를 따로 구하는 방식으로 구현했습니다. 혹시 후처리한다면 어떤 식으로 추려낼 수 있을까요??

2023-02-14 10:50 UTC, JungangHighschool commented on backend/src/contest/contest.service.ts
>    }
아 제가 잘못 생각한것 같네요. 그대로 하셔도 될 것 같습니다.

2023-02-14 10:51 UTC, JungangHighschool approved these changes

2023-02-14 11:20 UTC, Hyeongrok1 commented on backend/src/contest/contest.service.ts
> +
비록 작동에는 문제가 없지만 의미상 Partial로 보기에 어려울 수 있을 것 같아요. 그리고 제가 관여한 부분 외에도 contest.service.ts 파일의 코드가 전체적으로 비슷하게 `Partial<Contest>`로 반환 타입을 지정하고 있습니다. 그렇다면 contests 객체를 표현할 수 있는 새로운 타입을 만드는 것이 좋을까요?

2023-02-15 07:45 UTC, goo314 commented on backend/src/contest/contest.service.ts
> +        },
field 이름을 `isVisible`로 수정해주세요! 오류 납니당

2023-02-15 07:52 UTC, goo314 commented on backend/src/contest/contest.service.ts
> +        },
아하 conflict 전체 해결해주시면 될 것 같아요!

2023-02-16 07:21 UTC, goo314 submitted a review, later dismissed
contest.service.ts 파일에서
`getContests`와 `getContestsByGroupId`,
`getContestDetailById`와 `getGroupContestById`
method 각각 통일해주면 좋을 것 같아요! 로직은 똑같아서 코드를 합칠 수 있을 것 같아요 :)

2023-02-17 08:19 UTC, aintbe requested changes

2023-02-17 08:19 UTC, aintbe commented on backend/src/contest/contest.controller.ts
> +    return await this.contestService.getContests(undefined, groupId)
undefined 대신 정상적으로 `req.user.id` 보내주세요!

2023-02-17 08:19 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    user: AuthenticatedUser,
서비스 단에서는 AuthenticatedUser를 통째로 받을 필요가 없을 것 같아요! `userId: number`를 파라미터로 받는 게 좋을 것 같습니다 :D

2023-02-20 09:45 UTC, SH9480P approved these changes
고생하셨습니다.
테스트 코드는 고쳐야 할 부분이 더러 있지만, 이번 PR은 이쯤에서 마무리할게요. 
테스트 코드 작성은 issue를 따로 생성하여 구현해주세요.

2023-02-20 16:33 UTC, merged