344 feature backend pagination
skkuding/codedang pull request #372
Opened 2023-02-04 12:41 UTC by JungangHighschool

### Description
구현한 내용은 다음과 같습니다.

* workbook 모듈 pagination - controller에서 cursor query의 default value를 0으로 설정하였습니다.
 * workbook.service 의 getWorkbooksByGroupId 메서드 pagination
* contest 모듈 pagination - controller에서 cursor query의 default value를 0으로 설정하였습니다.
 * contest.service 의 getContests 메서드 pagination
 * contest.service 의 getContestsByGroupId 메서드 pagination
 * contest.service 의 getAdminOngoingContests 메서드 pagination
  - skip하지 않고 offset보다 1개 더 받아온 후, cursor와 일치하는 contest는 제거한 후 offset 에 맞춰 출력하도록 했습니다. 
 * contest.service 의 getAdminContests 메서드 pagination

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-02-05 07:02 UTC, SH9480P commented
PR 제목 바꿔주세요~
서버 실행하면 Public 데코레이터 없다고 나오는데 AuthNotNeeded로 변경(#366)되었으니 바꿔주세요~

2023-02-10 06:55 UTC, aintbe requested changes

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.controller.ts
> +    @Query('take', ParseIntPipe) offset: number
파라미터 이름 take로 통일해주세요~

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest-admin.controller.ts
> +    @Query('offset', ParseIntPipe) offset: number
파라미터 이름 take로 통일해주세요~

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    if (!myCursor) (skipNum = 0), (myCursor = 1)
일반적인 문법으로 수정해주세요...ㅎㅎ

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    offset: number
파라미터 이름 take로 통일해주세요~

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    offset: number
파라미터 이름 take로 통일해주세요~

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    const now = new Date(Date.now())
`new Date()`만 써도 현재 시간으로 만들어집니다!

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    const contets = await this.prisma.contest.findMany({
contets 오타 났어요!

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    } else if (results.length > offset) {
take(offset)이 음수일 경우가 고려되지 않았네요ㅜㅜ

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    //커서를 안보낸다. ==> default 설정
주석 지워주세요~

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    if (!myCursor) (skipNum = 0), (myCursor = 1)
요것도 일반적인 문법으로 수정해주세요!

2023-02-10 06:55 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    offset: number
파라미터 이름 take로 수정해주세요~

2023-02-10 06:55 UTC, aintbe commented on backend/src/workbook/workbook.service.ts
> +    offset: number
파라미터 이름 take로 수정해주세요~

2023-02-10 06:55 UTC, aintbe commented on backend/src/workbook/workbook.service.ts
> +    if (!myCursor) (skipNum = 0), (myCursor = 1)
일반적인 문법으로 수정해주세요~

2023-02-17 07:21 UTC, aintbe requested changes

2023-02-17 07:21 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +      },
id가 myCursor가 아닌 것을 조건으로 해서 쿼리 날리는 거 테스트해주세요!

2023-02-17 09:53 UTC, aintbe requested changes
src/common/constants.ts에서 아래 세 줄 지워주시고, contest나 notice에서 했던 것과 같은 방식으로 problem 모듈에 페이지네이션 넣어주세요!
```ts
export const PAGINATION_MAX_LIMIT = 10
export const PAGINATION_MIN_LIMIT = 0
export const PAGINATION_MIN_OFFSET = 0
```

2023-02-18 04:53 UTC, goo314 commented on backend/src/notice/notice.service.ts
> +    take: number
중간에 `cursor`도 쓰고 `myCursor`도 쓰던데 따로 구분해야 하는 이유가 있나요 ? 그리고 cursor와 offset을 같이 사용하니까 paginationDto 를 만들어서 쓰는건 어떨까요? 지금 common 폴더안에 paginationDto offset, limit을 cursor, offset으로 수정하면 될 것 같아요!

2023-02-22 09:49 UTC, aintbe approved these changes

2023-02-22 09:51 UTC, merged