feat(be): add validation for cursor value on pagination
skkuding/codedang pull request #390
Opened 2023-02-15 16:39 UTC by BEpaul

### Description

notice, contest, workbook domain의 cursor-based-pagination 기능이 구현된 메소드에서, 쿼리 파라미터인 cursor 값이 0 또는 음수일 때의 유효성 검사 기능을 추가하였습니다.

### Additional context

common 하위에 custom pipe를 추가하고, exception 폴더에 controller.exception.ts 파일을 추가하여 예외처리를 하였습니다.
cursor값이 0 또는 음수일 때에는 아래와 같이 에러메세지가 콘솔에 출력됩니다.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/104749551/219093054-d5bfa9b1-ecb2-4b6e-933c-eefc46cc4105.png">

> workbook 도메인에서 cursor-based-pagination 기능 구현이 진행중인 메소드에는 아직 적용하지 않았으며, 기능 구현이 완료되는대로 추가할 예정입니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

closes #374

2023-02-17 07:25 UTC, aintbe requested changes

2023-02-17 07:25 UTC, aintbe commented on backend/src/contest/contest-admin.controller.ts
> +//@UseGuards(RolesGuard)
주석 해결해주세요~

2023-02-17 07:25 UTC, aintbe commented on backend/src/contest/contest.controller.ts
> +  //@UseGuards(RolesGuard, GroupMemberGuard)
주석 해결해주세요~

2023-02-17 07:25 UTC, aintbe commented on backend/src/common/pipe/custom-validation.pipe.ts
> +  transform(value: any, metadata: ArgumentMetadata) {
value의 타입을 string으로 지정하고, 이후 코드에서 명시적으로 number로 변환해주세요!

2023-02-17 07:25 UTC, aintbe commented on backend/src/common/pipe/custom-validation.pipe.ts
> +    return value
`new DefaultValuePipe(0)`와 `ParseIntPipe`의 로직을 CursorValidationPipe에 포함시켜서, 컨트롤러에서 파이프 한 개만 쓰도록 하는 편이 좋을 것 같아요! 지금은 파이프가 너무 많이 붙어 있네요ㅠㅠ

2023-02-17 07:36 UTC, aintbe commented
라벨 설정하고 PR 내용에 체크도 해주세요~~!ㅎㅎ

2023-02-21 05:56 UTC, cho-to commented
group 모듈 `getGroups`에서도 pagination 구현한게 하나 있는데 혹시 그 부분에도 적용해주실 수 있으실까요 ?!

2023-02-22 09:10 UTC, BEpaul commented
> group 모듈 `getGroups`에서도 pagination 구현한게 하나 있는데 혹시 그 부분에도 적용해주실 수 있으실까요 ?!

네! 반영하겠습니다~

2023-02-22 10:30 UTC, aintbe approved these changes
머지해주세요!

2023-02-22 10:31 UTC, merged