378 contest detail problem api
skkuding/codedang pull request #394
Opened 2023-02-16 07:21 UTC by hbsongk

### Description
contest detail proble

### Additional context

1. contest detail 페이지에 있는 problem tab api 연결 완료했습니다.
2. problem tab에서 api 연결 시도를 했는데 rendering 할 때 버벅임이 생겨,
    contest detail 페이지에서 api 연결을 한 이후에,
    slot 형태로 problem tab에 paginationtable을 전달하였습니다.
    

paginationtable 행을 눌러 problem/id url로 이동을 한 이후에 뒤로가기 버튼을 눌렀을 시,
상단 탭(Top, Problem, Notice, Ranking)중 Top로 focused 되어 있는데,
Problem으로 고정되게 할 수 없나요? cookie나 section 쪽을 건드려야 하나요??

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-02-16 07:56 UTC, dotoleeoak commented
PR 제목 commitlint fail 이후에 PR 제목 수정했을 때, CI가 계속 fail 상태로 떠서 수정했습니다!
참고: https://github.com/deepakputhraya/action-pr-title/issues/4

2023-02-16 08:02 UTC, hbsongk commented
> PR 제목 commitlint fail 이후에 PR 제목 수정했을 때, CI가 계속 fail 상태로 떠서 수정했습니다! 참고: [deepakputhraya/action-pr-title#4](https://github.com/deepakputhraya/action-pr-title/issues/4)

아싸리요~~ 감사합니다람쥐

2023-02-16 08:31 UTC, goo314 requested changes

2023-02-16 08:31 UTC, goo314 commented on frontend/src/user/contest/components/problem.vue
>  ]
Field type 지워주세요~

2023-02-16 08:31 UTC, goo314 commented on frontend/src/user/contest/pages/[id]/index.vue
> +      </template>
어라 여기 1줄로 작성 가능한가요?

2023-02-16 08:38 UTC, hbsongk commented on frontend/src/user/contest/components/problem.vue
>  ]
네 지웠습니닷!!

2023-02-16 08:45 UTC, hbsongk commented on frontend/src/user/contest/pages/[id]/index.vue
> +      </template>
> 

넵 당근이죠~~ 수정완료 했습니다.

2023-02-16 08:46 UTC, hbsongk commented on frontend/src/user/contest/components/problem.vue
> +    @row-clicked="(row:any) => $router.push('/problem/' + row.problemId)"
> `@row-clicked="({id: number}) => $router.push('....'+id)"` 로 고치면 좋을 것 같아요!

넵 수정완료 했습니다~`

2023-02-20 08:12 UTC, goo314 requested changes

2023-02-20 08:12 UTC, goo314 commented on frontend/src/user/contest/components/problem.vue
> +})
여기 요청하는 url에 `componentId`가 달라질 수도 있어서 수정 부탁드릴게요!

2023-02-21 15:52 UTC, goo314 commented
> paginationtable 행을 눌러 problem/id url로 이동을 한 이후에 뒤로가기 버튼을 눌렀을 시,
> 상단 탭(Top, Problem, Notice, Ranking)중 Top로 focused 되어 있는데,
> Problem으로 고정되게 할 수 없나요? cookie나 section 쪽을 건드려야 하나요??

해당부분 #305 group page가 merge 되면서 useQuery로 수정된 상태입니다! tab을 누를때마다 query가 붙고 다른 페이지 이동 후 다시 돌아올때 이전 페이지로 돌아올 수 있어요!

main브랜치 merge 후 반영부탁드릴게요 ☺️

2023-02-23 08:04 UTC, goo314 commented
component 이름 PascalCase로 변경하고
contestId 값 사용할 수 있도록 코드 수정했습니다!
변수명도 알아보기 쉽게 바꿨어요 `Item` -> `Problem`

2023-02-23 08:43 UTC, st42597 commented on frontend/src/user/contest/pages/[id].vue
>        <Badge color="green">{{ time }}</Badge>
여기서 수정된 내용은 아니지만 시간 바뀔 때마다 badge가 꿈틀거려서 너비 고정하는거도 좋을거같아요

2023-02-23 08:48 UTC, st42597 approved these changes
굿

2023-02-23 08:52 UTC, goo314 approved these changes

2023-02-23 08:52 UTC, merged