fix(be): fix throw inappropriate exception
skkuding/codedang pull request #406
Opened 2023-02-21 05:20 UTC by jspark2000

### Description

이미 가입된 그룹에 가입 요청을 보낼경우
**EntityAlreadyExistException('Group join record')** 말고
**InternalServerErrorException()** 예외를 던집니다.

joinGroupById 메소드 내에 이미 가입한 그룹인지 판단하는 부분에서 `Array.includes()` 메소드를 사용하는데,
이를 `Array.some()` 메소드로 변경합니다.

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-02-21 06:23 UTC, cho-to commented
`Array.some()` 으로 바꾼건 좋은 것 같아요 ! 
그런데 `InternalServerErrorException(500)`은 사용자의 요청은 유효하지만 자체적인 서버 오류로 인해 요청을 수행할 수 없다는 의미이니(그리고 다른 서버 오류들이랑 헷갈릴수도 있을 것 같고...), `BadRequestException(400)`으로 message('이미 가입된 그룹입니다') 추가하는게 어떨까요?!

2023-02-21 06:46 UTC, aintbe requested changes
Json도 Object다 보니 서로 다른 인스턴스로 인식되어서 includes문이 먹히지 않았던 것 같네요! 수고하셨습니다~
- [x] 기존에 `EntityAlreadyExistException` 대신에 `ActionNotAllowedException`이 사용되고 있었어서, 해당 예외만 후자로 대체해주세요!

2023-02-21 18:06 UTC, cho-to commented
안쓰는 exception들 2개 지웠어요 !! 확인해주시면 감사하겠습니다 !

2023-02-22 01:28 UTC, SH9480P approved these changes
확인했습니다~

2023-02-22 06:14 UTC, aintbe approved these changes

2023-02-24 06:27 UTC, cho-to approved these changes

2023-02-24 11:32 UTC, dotoleeoak commented
@jspark2000 확인됐으면 merge 부탁드릴게요!

2023-02-28 02:49 UTC, merged