fix(be): add controller for users not logged in
skkuding/codedang pull request #420
Opened 2023-02-23 05:53 UTC by Hyeongrok1

### Description

`AuthNotNeeded` 데코레이터가 붙은 엔드포인트에서는 `request.user`가 항상 `undefined`가 되므로 유저가 참여하는 대회의 정보를 알 수 없게 됩니다. 즉, 로그인한 상태를 반영할 수 없습니다.

따라서 `PublicContestController`에서 `AuthNotNeeded` 데코레이터를 제거하고 로그인하지 않은 사람들을 대상으로 하는 `GuestContestController`를 따로 추가합니다.

#416 참고해주세요

### Additional context

로그인한 유저의 엔드포인트: /contest/auth
로그인하지 않은 유저의 엔드포인트: /contest

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-02-24 11:15 UTC, aintbe requested changes

2023-02-24 11:25 UTC, Hyeongrok1 commented on backend/src/contest/contest.controller.ts
>      registeredUpcoming?: Partial<Contest>[]
시도해봤는데 optional을 제거하면 타입스크립트 오류가 뜨더라고요..

2023-02-24 12:07 UTC, aintbe commented on backend/src/contest/contest.controller.ts
> +    return await this.contestService.getContests(req.user?.id, PUBLIC_GROUP_ID)
@Hyeongrok1 origin/main merge 후에 작업하신 게 맞나요?! 마지막 PR에서 groupId에 대한 default 값 처리가 되어 있는데 해당 부분이 반영되지 않은 것 같아서요!

2023-02-24 12:27 UTC, Hyeongrok1 commented on backend/src/contest/contest.controller.ts
> +    return await this.contestService.getContests(req.user?.id, PUBLIC_GROUP_ID)
혼자 이상한 오해를 하고 잘못 작업했었네요.. 머지하고 다시 고쳤습니다!

2023-02-25 07:59 UTC, dotoleeoak commented on backend/src/contest/contest.controller.ts
>      registeredUpcoming?: Partial<Contest>[]
아래처럼 함수 overloading 기능 쓰면 해결 가능합니다!

```ts
export class ContestService {
  async getContestsByGroupId(): Promise<{
    ongoing: Partial<Contest>[]
    upcoming: Partial<Contest>[]
    finished: Partial<Contest>[]
  }>

  async getContestsByGroupId(
    userId: number,
    groupId?: number
  ): Promise<{
    registeredOngoing: Partial<Contest>[]
    registeredUpcoming: Partial<Contest>[]
    ongoing: Partial<Contest>[]
    upcoming: Partial<Contest>[]
    finished: Partial<Contest>[]
  }>

  async getContestsByGroupId(
    userId = -1,
    groupId = OPEN_SPACE_ID
  ): Promise<{
    registeredOngoing?: Partial<Contest>[]
    registeredUpcoming?: Partial<Contest>[]
    ongoing: Partial<Contest>[]
    upcoming: Partial<Contest>[]
    finished: Partial<Contest>[]
  }> {
    if (userId === -1) {
      // ...
    }
  }
}
```

2023-02-25 08:04 UTC, dotoleeoak commented on backend/src/contest/contest.controller.ts
>      registeredUpcoming?: Partial<Contest>[]
또는 아래처럼 하나로 합칠 수도 있어요...!

```ts
export class ContestService {
  async getContestsByGroupId<T extends number>(
    userId?: T,
    groupId?: number
  ): Promise<
    T extends undefined
      ? {
          ongoing: Partial<Contest>[]
          upcoming: Partial<Contest>[]
          finished: Partial<Contest>[]
        }
      : {
          registeredOngoing: Partial<Contest>[]
          registeredUpcoming: Partial<Contest>[]
          ongoing: Partial<Contest>[]
          upcoming: Partial<Contest>[]
          finished: Partial<Contest>[]
        }
  >

  async getContestsByGroupId(userId = -1, groupId = OPEN_SPACE_ID) {
    if (userId === -1) {
      // ...
    }
  }
}
```

2023-02-26 09:52 UTC, Hyeongrok1 commented on backend/src/contest/contest.controller.ts
>      registeredUpcoming?: Partial<Contest>[]
아래 방법으로 해결했습니다! 감사합니다!!

2023-03-02 06:57 UTC, aintbe approved these changes

2023-03-02 06:57 UTC, aintbe commented
수고하셨습니다! 머지해주세요~!

2023-03-02 10:23 UTC, merged