feat(fe): group notice api connected
skkuding/codedang pull request #423
Opened 2023-02-23 08:29 UTC by EliseCho13

close #409 
group 페이지의 개별 전체 공지를 해당 api와 연결했습니다. 토큰은 임시로 발급하여 넣어두었습니다.
shownItems 대신 단일 배열로 바꾼 items에 ref를 씌웠으며, filter 함수는 추후 api로 대체할 것이므로 주석처리해두었습니다.
offset은 임시로 1로 지정하였으며 시간은 표준시간 변환 등의 작업 없이 date를 단순히 slice 했습니다.

2023-03-24 07:21 UTC, eunnbi commented
`main` 브랜치 merge 해주시고, 토큰 지워주세요!

2023-03-24 08:13 UTC, eunnbi commented
백엔드 Group Notice Get API 문서 최신화 필요

![image](https://user-images.githubusercontent.com/89760088/227462415-cdf95310-d5fc-41eb-a887-ee7de4f54a94.png)

2023-03-24 08:26 UTC, eunnbi requested changes

2023-03-24 08:26 UTC, eunnbi commented on frontend/src/user/group/components/Notice.vue
> +  .get(`/api/group/${props.id}/notice?offset=1`, {
백엔드 API 문서가 최신화가 안 되어 있는데, query parameter로 `cursor`와 `take`가 필요합니다!
- `/notice?take=10`: 처음 10개 요청
- `/notice?cursor=1&take=10`: id가 1인 row 다음부터 10개 요청

2023-03-29 11:25 UTC, EliseCho13 commented on frontend/src/user/group/components/Notice.vue
> +  // const total = []
주석 아예 없애면 prettier가 필터 함수 없애라고 해서 TODO를 함수 내로 옮겼습니다

2023-03-29 12:57 UTC, eunnbi commented on frontend/src/user/group/components/Notice.vue
> +  .get(`/api/group/${props.id}/notice?offset=1`, {
`cursor` 를 `ref` 값으로 해주세요!

2023-05-10 10:27 UTC, eunnbi requested changes

2023-05-10 10:27 UTC, eunnbi commented on frontend/src/user/group/components/Notice.vue
> +    items.value = res.data
43번 줄 코드 지워주세요! 중복 아이템이 발생합니다.

2023-06-16 13:02 UTC, eunnbi commented
Issue #432 논의 필요해보임.

2023-07-14 04:26 UTC, Kohminchae approved these changes

2023-07-14 04:28 UTC, merged