feat(be): seperate logics get finished contests
skkuding/codedang pull request #458
Opened 2023-04-10 08:11 UTC by Anzanda

### Description

대회들을 불러오는 API는 `ongoing`, `upcoming`, `finished`로 구분되어 받습니다.
이 중 `finished`는 다른 것들과 분리될 필요가 있습니다.
- 대회가 원활하게 진행된다면 종료된 대회가 훨 많아집니다.
- 그렇기에 추가로 페이지네이션 도입이 필요합니다.
- 나머지 2개는 `User`와 관련있지만 `finished`는 그렇지 않습니다.

본 PR은 `ongoing`, `upcoming`을 'Alive'라는 개념으로 묶어 finished와 따로 움직이도록 메소드를 분리하였습니다.

### Additional context

코딩하면서 주의 깊은 리뷰 받았으면 좋겠다 싶은 것들이 있었습니다.
1. prisma로 contests들을 가져오는 로직을 하나의 함수로 만들었습니다. `findContestsByGroupId`입니다. 중복이 여러개 생겨서 본능적으로 분리하였는데 어찌보면 레포지토리 패턴같기도 해서 고민입니다. 스쿠딩 컨텍스트에선 이게 허용될지 모르겠습니다. (해당 커밋 00c83d57621228a6be567126c02af9dba10f8a29)
2. 테스트 작성이 익숙치 않습니다. `getFinishedContests`에 관한 테스트를 **단 하나** 작성하였습니다 ㅎㅎ;; 이래도 괜찮을까요? 테스트는 어떻게 짜는게 좋을까요?

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-04-25 15:33 UTC, aintbe commented on backend/apps/client/src/contest/contest.service.spec.ts
> +        await service.getAliveContestsByGroupId(undefinedUserId, groupId)
이 부분에서 finished 안 없애서 test fail 나는 거 같아요! 수정해주세요~

2023-04-25 15:33 UTC, aintbe commented on thunder-tests/thunderCollection.json
> +        "name": "Get finished contests",
닥스 엔드포인트 "Get all contests"를 "Get ongoing & upcoming contests"로 수정하는 게 혼선 방지에 좋을 것 같아요!

2023-04-25 15:33 UTC, aintbe commented on thunder-tests/thunderclient.json
> +    "docs": "# Get all contests\n\n종료된 대회를 제외한 모든 목록을 불러옵니다.  \n대회의 진행 상태에 따라 구분합니다. (ongoing, upcoming)"
기존 설명이 좀 모호했던 것 같은데, '~ 제외한 Open Space의 모든 대회 목록'으로 수정 부탁드립니다ㅠㅠ

2023-04-25 15:33 UTC, aintbe commented on thunder-tests/thunderclient.json
>      "method": "GET",
url에서 group id를 1로 주면 open space 함수와 동일하게 동작합니다! 기존 닥스에서 이 부분이 확인되지 않고 넘어간 것 같은데 정확하게 동작하는 게 맞는지 체크할 수 있도록 group id를 2로 바꿔주세요!

2023-04-25 15:33 UTC, aintbe commented on thunder-tests/thunderclient.json
> +    "url": "/group/1/contest/finished?take=10",
여기도 마찬가지로 group id 2로 수정해주세요! 그리고 다른 리퀘스트(예: get all problems) 보시면 take로 정확하게 잘리는 게 맞는지 확인하는 테스트도 있는데, 여기에도 추가되면 좋을 것 같습니다!ㅎㅎ

또, 지금 PreRun으로 로그인이 등록되어 있지 않아서, 아마 다른 리퀘스트를 날려보지 않은 상태로 이 리퀘스트를 바로 날리면 테스트가 fail날 거예요 :D 다른 엔드포인트 참고하셔서 PreRun에 로그인 과정 추가해주세요!

2023-04-30 11:13 UTC, Anzanda commented on backend/apps/client/src/contest/contest.service.ts
>      })
좋습니다. Resolve하면서 느낀건데 하나로 묶는게 어색하네용!

2023-04-30 12:03 UTC, Anzanda commented on backend/apps/client/src/contest/contest.service.ts
> +      ...(cursor && { cursor: { id: cursor } }),
이건 어쩔 수 없을 거 같아요... 일단 skip은 변수로 썼어요.
cursor가 문제에요.
cursor가 undefined혹은 '0'이라면 `cursor: { id : cursor }`필드 자체가 생기면 안 돼요. 클라이언트가 커서를 핸들링 하고 있지 않으니까요.
그러면 default값을 주면 되지 않냐? 생각했어요.(+ 밑에 Admin쪽은 이렇게 돼있드라구요.) 그런데 finished contest특성상 첫번째 레코드의 id가 **1**일 것이라는 보장이 없어요. (저희 모킹 데이터에선 '2'랍니다.)
즉, 저 괴랄한 친구를 없앨라면 if문으로 cursor가 있을 때, 없을 때로 분기를 해야돼요. 제 생각으로는 이게 마지막 보루였어요.)
저는 이렇게 할 바엔 괴랄한 친구를 사용하는 게 더 낫다고 판단했습니다.
리뷰어님은 어떠신가여???

2023-05-02 11:59 UTC, aintbe requested changes

2023-05-02 11:59 UTC, aintbe commented on backend/apps/client/src/contest/contest.service.ts
> +      ...(cursor && { cursor: { id: cursor } }),
말씀하신 대로 notice 같은 다른 모듈에 비해서는 복잡해질 수밖에 없는 상황인 것 같네요! 그런데 그걸 감안해도 가독성이 너무 떨어지는 코드라서 수정하는 편이 좋을 것 같아요! if else문으로 비슷한 코드가 나열되는 게 싫으신 거라면 `findMany`의 argument로 들어가는 object를 정의하는 코드를 if else 문에 넣고, 그 다음에 이 object로 해당 함수를 호출하는 게 어떨까요?

2023-05-02 13:16 UTC, aintbe commented
새로 작성하신 테스트에서 fail나는데 확인 부탁드려요~ @Anzanda

2023-05-05 04:27 UTC, Anzanda commented on backend/apps/client/src/contest/contest.service.ts
> +      ...(cursor && { cursor: { id: cursor } }),
if-else로 해결하겠습니다. findOption을 밖으로 뺴려고 하니까 type error뜨네요.

2023-05-05 07:05 UTC, aintbe commented on backend/apps/client/src/contest/contest.service.ts
> +      ...(cursor && { cursor: { id: cursor } }),
Type Error는 [여기](https://stackoverflow.com/questions/68208946/prisma-findmany-input-type) 참고하셔서 해결하시면 될 것 같아요! 원래 중복을 줄이려고 하셨던 거니까 이쪽이 좀 더 의도에 가까울 것 같네요ㅎㅎ

2023-05-07 03:04 UTC, Anzanda commented on backend/apps/client/src/contest/contest.service.ts
> +      ...(cursor && { cursor: { id: cursor } }),
오 일케하니까 문제없군요 감사합니다

2023-06-15 10:54 UTC, aintbe approved these changes

2023-06-15 10:56 UTC, merged