453 feature adminproblem graphql 적용
skkuding/codedang pull request #483
Opened 2023-06-15 11:35 UTC by JungangHighschool

### Description

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-07-04 11:33 UTC, aintbe requested changes
어드민 그룹 모듈을 참고해서 보시면 리뷰 이해가 쉬울 거라서, 먼저 머지하시고 작업해주세요!

2023-07-04 11:33 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +    } = problemCreateInput
위의 리뷰들을 반영하면 input에서 빼야 할 값은 problemTestcase 하나밖에 남지 않으니까,
```suggestion
    const { testcases, ...problem } = input
    return await this.prisma.problem.create({
      data: {
        problemTestcase: {
          create: testcases
        }
      })
```
이렇게 가면 될 것 같아요!

2023-07-04 11:33 UTC, aintbe commented on backend/apps/admin/src/problem/dto/request-problem.dto.ts
> +}
일단 여기서 `groupId` (가드 때문에), `cursor` (CursorValidationPipe 써야 해서), `take` (의미적으로 cursor랑 세트니까) 세 가지는 별도의 argument로 분리해주는 게 맞고, 생성자/레벨/언어별로 따로 조회할 수 있는 기능은 아직 기획에 없어서 나머지 세 가지는 그냥 없애주시면 될 것 같아요.

2023-07-04 11:33 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +      throw new NotFoundException()
catch문 안 써도 prisma에서 자동으로 보내줍니다~

2023-07-04 11:33 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +    const { problemId: _a, difficulty: _b, ..._data } = updateProblemInput
여기서 쓰신 문법은 [구조 분해 할당](https://basarat.gitbook.io/typescript/future-javascript/destructuring)이라고 불리는 문법이에요! 우항에 주어진 object의 property를 분해해서 좌항의 변수들에 나누어 할당해주는 문법입니다. 그러니까
```ts
const updateProblemInput = {
  problemId: 1,
  difficulty: 2,
  rest1: 3,
  rest2: 4
}
const { problemId: _a, difficulty: _b, ..._data } = updateProblemInput /*
const _a = 1
const _b = 2
const _data = {
  rest1: 3,
  rest2: 4
} */
```
쓰신 코드는 제일 아래의 주석과 똑같은 거예요! 그래서 처음부터 아래처럼 할당하시면, 뒤에서 problemId나 difficulty를 굳이 다시 만들어줄 필요가 없습니다. 그리고 difficulty는 처음부터 required 필드로 설정하는 게 좋을 것 같아요!
```suggestion
const { problemId, difficulty, ...problem } = updateProblemInput
```

2023-07-04 11:33 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +    }
이렇게 구현하면 problem이 기존에 없어서 업데이트가 안 된 건지, update 작업에서 내부적으로 fail이 난 건지 알 수 없으니까 update 전에 find로 problem을 찾아보는 로직을 넣어주세요!

2023-07-04 11:33 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +      })
where절에 groupId도 넣어줘야 해요! 이유는 아래에서 설명할게요~

예를 들어, 유저가 그룹2의 리더이고 컨테스트1이 그룹1의 대회라고 할게요. 유저가 /group/2/contest/1 이런 식으로 접근하면 (1) 전역 가드(GroupLeaderGuard)는 유저가 그룹2의 리더인지만 확인하기 때문에 이를 통과시키고, (2) 이 함수도 조회하고자 하는 대회가 어떤 그룹에 속했는지 확인해주지 않아서, 결과적으로 유저는 접근 권한이 없는 리소스에 접근할 수 있게 됩니다. 하지만 위에서 말한 것처럼 groupId 조건까지 확인해주면 이런 문제가 해결돼요!

2023-07-04 11:33 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +      })
혹시 여기서 `return await this.prisma.problem.delete(...)`를 쓰면 어떻게 되나요?

2023-07-04 11:33 UTC, aintbe commented on backend/prisma/schema.prisma
> +  id          Int      @id @default(autoincrement()) // referential actions(modified)
이 주석은 어떤 의미인가요?

2023-07-04 11:33 UTC, aintbe commented on backend/prisma/schema.prisma
> +  tag       Tag     @relation(fields: [tagId], references: [id], onDelete: Restrict, onUpdate: Restrict)
이 테이블은 relation 테이블이라서 태그가 사라지면 그냥 함께 사라지도록 설정해주셔도 괜찮습니다. 둘 다 Cascade로 바꿔주세요!

2023-07-04 11:33 UTC, aintbe commented on backend/apps/admin/src/problem/mock/problem.mock.ts
> +export const problems: Problem[] = [
테스트 시 실제 테스트용 DB를 연결할 생각이라, 지금 모킹 파일은 그냥 테스트 파일이랑 통합해도 괜찮을 것 같아요!

2023-07-05 12:52 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.service.ts
> +      })
약간 이해가 안됩니다. 태그를 따로 만드나요?

2023-07-05 13:08 UTC, JungangHighschool commented on backend/apps/admin/src/problem/dto/request-problem.dto.ts
> +}
FE 팀이 제출한 Group Problem API List에서 선택한 조건에 맞는 Problem을 조회하는 'Group Import Problem'라는 이름의 검색 API를 요청했는데 구현에서 제외할까요?

2023-07-05 14:03 UTC, aintbe commented on backend/apps/admin/src/problem/dto/request-problem.dto.ts
> +}
아 import 관련 페이지 때문에 필요했던 거였군요! 그러면 생성자별로 조회하는 기능은 잘못 들어간 것 같아서 이건 제외하고, 레벨/언어는 둘 다 리스트로 받아오도록 구현하는 게 맞는 것 같습니다!

2023-07-05 14:33 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.service.ts
> +      })
조금 자세히 설명 가능할까요?

2023-07-05 14:37 UTC, JungangHighschool commented on backend/apps/admin/src/problem/dto/request-problem.dto.ts
> +}
네

2023-07-05 14:42 UTC, JungangHighschool commented on backend/apps/admin/src/problem/mock/problem.mock.ts
> +export const problems: Problem[] = [
build시 client/group의 mock 파일들에서 오류가 발생하는데 확인 가능할까요?
로컬에서는 일시적으로 해결하고 정상적으로 build 했지만 제가 수정해도 되나 싶습니다.

2023-07-05 15:44 UTC, aintbe commented on backend/apps/admin/src/problem/mock/problem.mock.ts
> +export const problems: Problem[] = [
mock.ts와 service.spec.ts를 합쳐달라는 뜻이었는데, 두 개를 합치면 에러가 난다는 건가요, 아니면 그거랑 상관이 없이 지금 그런 이슈가 있다는 건가요???

2023-07-06 13:25 UTC, JungangHighschool commented on backend/apps/admin/src/problem/mock/problem.mock.ts
> +export const problems: Problem[] = [
아, admin/src/problem에 관한 이야기가 아니라, client/src/group에서 에러가 난다는 이야기였습니다. 어느 comment에 달아야 하는 내용인지 모르겠어서 이곳에 남겼습니다. 제 branch의 cl/build fail 로그 참고 바랍니다.

2023-07-06 13:33 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.service.ts
> +      })
Group  resource에 접근하는 요청에 대하여 resolver에서 groupId를 비교해 보도록 수정했습니다.

2023-07-06 13:34 UTC, JungangHighschool commented on backend/prisma/schema.prisma
> +  id          Int      @id @default(autoincrement()) // referential actions(modified)
별 의미 없이 붙이고 실수로 제거하지 않은 듯 합니다.

2023-07-06 13:40 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.service.ts
> +    } = problemCreateInput
tag의 경우, 위 comment를 반영해 프런트에서 배열로 받아온 것을 객체들의 배열로 전환해 입력되도록 수정했습니다. 따라서, testcase 뿐 아니라 tag도 삭제 시키도록 수정하겠습니다.

2023-07-06 13:44 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.service.ts
> +    }
위 수정 내역들과 결부된 질문인데, 본 service 로직 전에 사전에 요청의 타당성 여부를 검사하는 로직을 resolver에 배치해도 괜찮을까요?

2023-07-07 09:31 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +    }
요청의 타당성 여부를 검사한다는 게 모호한데 정확히 어떤 부분을 검사한다는 건가요?

2023-07-07 09:34 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +      })
그냥 `return await this.prisma.problem.delete(...)` 이런 식으로 설정하면 어떤 값이 리턴되는지를 여쭤본 거였는데, 직접 해보니 이렇게 해도 정상적으로 삭제된 problem이 리턴되네요! 굳이 변수에 할당 안 하고 바로 리턴하셔도 될 것 같습니다.

2023-07-07 10:17 UTC, aintbe requested changes

2023-07-07 10:17 UTC, aintbe commented on backend/apps/admin/src/problem/problem.resolver.ts
> +    @Args('input') getGroupProblemsInput: GetGroupProblemsDto
변수명이 너무 길어서 보기가 어려운 것 같아요. 다른 input이 있어서 구분할 일이 있는 상황이 있는 게 아니니까, 이것도 그냥 `input`으로 통일하는 게 어떨까요?

2023-07-07 10:17 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +  async create(createdById: number, problemCreateInput: CreateGroupProblemDto) {
이것도 기존 컨벤션 따라서 `get/create/update/delete${resource-name}[s]`으로 바꿔주세요!

2023-07-07 10:45 UTC, aintbe requested changes
get 서비스 쪽은 아직 이전에 말씀드린 리뷰가 반영되지 않은 것 같아서, 다시 반영되면 리뷰 남기겠습니다. 수정 후에 멘션 남겨주세요!

2023-07-07 10:45 UTC, aintbe commented on backend/apps/admin/src/problem/dto/create-problem.dto.ts
> +  declare tag?: Array<number>
이 두 개는 required 필드로 바꿔주셔도 될 것 같습니다. 그게 서비스 로직을 쓸 때 더 깔끔하고, 프론트에서도 정보가 없으면 그냥 empty array를 넣어주면 되는 거라 문제가 없으니까요. 그리고 group 쪽에서 field를 추가할 때 `declare` 키워드를 썼던 건 이미 존재하는 필드를 override하기 때문이었어요! 여기서는 둘 다 새로운 필드라 아마 키워드를 떼셔도 괜찮을 겁니당!

2023-07-07 10:45 UTC, aintbe commented on backend/apps/admin/src/problem/dto/create-problem.dto.ts
> +export class CreateGroupProblemDto extends ProblemUncheckedCreateInput {
그리고 createdBy는 받을 일이 없으니까`ProblemUncheckedCreateWithoutCreatedByInput`를 extend하는 게 더 좋을 듯하네요!

2023-07-07 10:45 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +        ..._data,
주어진 input 타입에 optional로 있을 수 있는 필드가 많기 때문에, data를 검증 없이 전부 넣지 말고 필드별로 명확하게 할당해주시는 게 좋을 것 같아요...!

2023-07-07 10:45 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +        problemTestcase: problemTestcase,
```suggestion
        problemTestcase: {
          create: testcases
        },
```
여기도 위의 로직을 이렇게 바꿔주는 게 더 깔끔할 것 같긴 한데, 이 부분은 나중에 수정될 부분이라 크게 신경쓰지 않으셔도 될 것 같습니다.

2023-07-07 10:47 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +        ..._data,
그리고 data 앞에 _를 붙인 건 private임을 강조하기 위함인가요...? 지금은 data는 클래스 멤버가 아니니 그런 정보는 반영하지 않아도 될 것 같아요!

2023-07-08 08:19 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.service.ts
> +        ..._data,
_data는 기존에 작성되었다가 수정 중 삭제된 코드와 관련된 변수여서 _가 붙여졌던 것 같습니다. 수정하겠습니다.

DTO를 사용하면 별도의 검증없이 할당할 수 있지 않나요? 위 코멘트에서 물어보셨던 'Object.defineProperties(CreateGroupProblemInput.prototype, { ...'와 같은 코드가 'craetedTime'과 같이 자동으로 생성되어야 할 metadata들을 fe에서 작성하지 못하도록 제한하는 역할을 합니다. tag, testcase를 새로운 property로 정의하고, 요청받아 별도로 파싱하는 작업을 거치게 한 것 또한 별도의 검증 과정을 거치지 않게 하기 위함이었습니다. 정확히 optional이라는 의미를 파악하지 못하겠지만, CreateGroupProblemInput이라는 DTO를 사용하면 별도의 할당 과정이 불필요하다고 생각합니다.

2023-07-08 08:29 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.resolver.ts
> +  }
Open_space의 관리자를 다른 그룹 관리자와 구별해서 취급 안해도 되나요?

2023-07-09 07:02 UTC, JungangHighschool commented on backend/apps/admin/src/problem/dto/request-problem.dto.ts
> +}
일관성 있게 DTO를 만들어 사용하는 것보다 그냥 argument 로 처리하는게 낫나요?

2023-07-09 07:29 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.service.ts
> +    }
뒤 코멘트에서 답변해주신 것 같습니다. groupId의 타당성 여부나 레코드 존재여부를 판별하는 것을 resolver에서 해야하나 혹은 service에서 해야 하나에 관한 질문이었습니다.

2023-07-09 07:30 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.service.ts
> +        ..._data,
Omittype()을 사용해서 사용자에 의해 작성되어서는 안되지만 optional로 있을 수 있는 필드를 제거해 주었습니다.

2023-07-09 08:24 UTC, dotoleeoak commented on backend/prisma/schema.prisma
> +  // emitCompiled       = true
이 부분은 push하지 말아주세요! (이대로 적용되면 CI에서 fail나요)

2023-07-12 13:07 UTC, JungangHighschool commented
> 

수정했습니다

2023-07-13 08:57 UTC, aintbe requested changes
썬더클라이언트의 _db-backup 폴더와 coding-platform-api는 없어져야 합니다! 그런데 자동으로 삭제가 안 된 걸 보면 main merge가 꼬인 것 같기도 한데 전부 pull된 게 맞나요??

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +    if (groupId != input.groupId) {
input으로 groupId를 새로 받아올 이유가 없을 것 같아요. 그냥 argument로 받아온 groupId로 레코드 만들고 input으로 해당 필드 안 받아오도록 설정해주세요!

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/problem.resolver.ts
> +    )
여기서 두 가지 종류의 예외가 발생할 수 있을 것 같아요! DB에 뭔가 문제가 생겨서 create를 못 하는 경우와, 유저가 실제로 존재하지 않는 tag id를 넘겨줘서 create가 안 되는 경우 두 개로요! 첫 번째는 서버 문제라 따로 알려주지 않아도 되지만 두 번째는 사용자에게 정보를 알려줘야 하니까 예외 처리 코드 넣어주는 게 좋을 것 같습니다!ㅎㅎ (참고로 두 번째는 PrismaClientKnownRequestError에 에러 코드가 P2003인 경우를 catch하시면 돼요~ cf. https://www.prisma.io/docs/reference/api-reference/error-reference)

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/problem.resolver.ts
> +    return await this.problemService.getGroupProblem(groupId, input)
서비스 함수 내에 throw문이 있으니까 여기서 예외 처리해주셔야 합니다!

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/problem.resolver.ts
> +    return await this.problemService.deleteGroupProblem(groupId, input)
서비스 함수 내에 throw문이 있으니까 여기서 예외 처리해주셔야 합니다!

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/problem.resolver.ts
> +    return await this.problemService.updateGroupProblem(groupId, input)
서비스 함수 내에 throw문이 있으니까 여기서 예외 처리해주셔야 합니다!

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +      }
여기도 이제 eslint disable 안 해도 괜찮을 거예요ㅎㅎ 삭제해주세요!

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/dto/create-problem.dto.ts
> +  ] as const
여기서 id, createdById, groupId, submission도 빠져야 합니다!

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/dto/update-problem.dto.ts
> +  problemId: number // modify
그리고 problemId를 새로 받아올 것 없이 id에서 optional만 해제해줘도 될 것 같아요!

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/dto/update-problem.dto.ts
> +  'createdById'
여기서 groupId, submission도 빠져야 합니다!

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/dto/create-problem.dto.ts
> +  ] as const
그리고 빠질 것들 고려하면 ProblemUncheckedCreate... 말고 ProblemCreate...를 쓰는 게 나을 것 같아요!

2023-07-13 08:57 UTC, aintbe commented on backend/apps/admin/src/problem/problem.service.ts
> +    return await this.prisma.problem.update({
이렇게 하면 problem tag 목록, testcase 목록 등을 수정하고 싶을 때 자동으로 업데이트가 되나요? 안 될 것 같은데 로직 확인해주세요!

2023-07-13 11:04 UTC, JungangHighschool commented on backend/apps/admin/src/problem/dto/create-problem.dto.ts
> +  ] as const
'createdById'는 조회되지 않습니다. 나머지는 수정했습니다.

2023-07-13 11:07 UTC, JungangHighschool commented on backend/apps/admin/src/problem/problem.service.ts
> +    return await this.prisma.problem.update({
아 그게 ... 기존 것 삭제, 기존 것 수정, 새로운 것 추가 등 tag와 testcase에 대해서 여러가지 작업을 상상해 볼 수 있어서, problemTag와 problemTestcase는 새로운 type을 만들지 않고 generated 된 것 그대로 fe에서 사용하도록 하였습니다.

2023-07-13 11:09 UTC, JungangHighschool commented on backend/apps/admin/src/problem/dto/create-problem.dto.ts
> +  ] as const
> 그리고 빠질 것들 고려하면 ProblemUncheckedCreate... 말고 ProblemCreate...를 쓰는 게 나을 것 같아요!

후자가 fe에서 쓰기 조금 불편할 것 같습니다. type을 수정하면 되긴 하지만 그렇게 되면 이전 버전과 다를 바 없고 서비스에서 추가적인 작업이 필요할 것 같아 기존 것을 유지하는 것이 바람직하다고 생각됩니다.

2023-07-13 12:07 UTC, aintbe requested changes

2023-07-13 12:07 UTC, aintbe commented on backend/apps/admin/src/problem/dto/create-problem.dto.ts
> +  ] as const
후자가 OmitType 이용해서 뺄 것들이 오히려 적어보여서 제안해본 거였는데, FE에서 불편할 것 같다는 게 어떤 의미인지 물어봐도 될까요?ㅎㅎ `@generated`의 파일이 타입으로 지정되어 있는 필드들(FE에서 귀찮을 만한 필드들)은 어차피 omit type으로 빠지게 되지 않나요?

2023-07-13 12:07 UTC, aintbe commented on backend/apps/admin/src/problem/problem.resolver.ts
> +        throw new NotFoundException(err.message)
여기서 이전에 말씀드렸던 에러 코드도 확인해주셔야 합니다!! 그리고 NotFound보다는 Unprocessable이 더 가까울 것 같아요!

2023-07-31 20:28 UTC, aintbe approved these changes

2023-07-31 20:35 UTC, merged