fix(fe): connect contest & notice API to home page
skkuding/codedang pull request #519
Opened 2023-06-22 12:31 UTC by dayongkr

### Description

- home 
  - notice
    - api로 글 3개만 가져와서 표시
  - contest
    - api에 take 기능이 없어서 전체를 가져오고 oncoming, upcoming 중 3개를 표시

close #510 

### Before submitting the PR, please make sure you do the following

- [x ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-06-24 07:45 UTC, aintbe commented
contest에서 oncoming, upcoming은 개수 제한 없이 항상 전체를 보여주고 finished는 구역을 따로 나눠서 pagination을 넣는 것으로 기획했었어요! (oncoming+upcoming을 합쳐봤자 그리 많지 않을 거라서요) 개수 조절하는 부분은 따로 구현하지 않으셔도 될 것 같습니다ㅎㅎ

2023-06-24 07:46 UTC, aintbe commented
contest에서 oncoming, upcoming은 개수 제한 없이 항상 전체를 보여주고 finished는 구역을 따로 나눠서 pagination을 넣는 것으로 기획했었어요! (oncoming+upcoming을 합쳐봤자 그리 많지 않을 거라서요) 개수 조절하는 부분은 따로 구현하지 않으셔도 될 것 같습니다ㅎㅎ

2023-06-24 13:26 UTC, dayongkr commented
> contest에서 oncoming, upcoming은 개수 제한 없이 항상 전체를 보여주고 finished는 구역을 따로 나눠서 pagination을 넣는 것으로 기획했었어요! (oncoming+upcoming을 합쳐봤자 그리 많지 않을 거라서요) 개수 조절하는 부분은 따로 구현하지 않으셔도 될 것 같습니다ㅎㅎ

고쳤습니다~

2023-06-25 03:30 UTC, eunnbi requested changes

2023-06-25 03:30 UTC, eunnbi commented on frontend/src/user/home/pages/index.vue
> +interface ContestItem extends Item {
`ContestItem` 대신 [contest의 index 페이지](https://github.com/skkuding/codedang/blob/514-connect-api-contest-notice-tab/frontend/src/user/contest/pages/index.vue#L16)에 있는 `Contest` 인터페이스를 import 해서 사용하면 어떨까요??? `Contest` 인터페이스의 `startTime`, `endTime` 속성 타입은 `string`으로 바꿔야 할 것 같네요. 바꿔도 contest 페이지에 영향은 없어요!

2023-06-26 05:55 UTC, dayongkr commented on frontend/src/user/home/pages/index.vue
> +interface ContestItem extends Item {
고쳤습니다~

2023-06-26 07:45 UTC, eunnbi approved these changes

2023-06-26 08:23 UTC, merged