fix(fe): connect API in a contest detail page
skkuding/codedang pull request #558
Opened 2023-06-24 12:43 UTC by dayongkr

### Description

- Top, Notice, Problem 탭 API 연결 완료
- Contest startTime, endTime 기준으로 진행 중이면 초록색, 아니면 빨간색으로 뱃지 수정
- Rank 탭 주석 처리

#525 
---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-06-24 13:45 UTC, dotoleeoak requested changes

2023-06-24 13:45 UTC, dotoleeoak commented on frontend/src/user/contest/pages/[id].vue
> +let endTime = ''
`startTime`이랑 `endTime`은 ref로 할당해야될 것 같아요! 지금대로면 api호출 후 값이 바뀌어도 39번째 줄에서 변경된 값이 반영이 안돼요

2023-06-25 02:21 UTC, dayongkr commented on frontend/src/user/contest/pages/[id].vue
> +let endTime = ''
적용했습니다!

2023-06-25 02:46 UTC, dotoleeoak approved these changes

2023-06-25 02:46 UTC, dotoleeoak commented
수고하셨고 'squash and merge' 해주시면 돼요~

2023-06-25 03:25 UTC, merged