feat(be): implement admin contest module with graphql (#517)
skkuding/codedang pull request #573
Opened 2023-06-27 12:37 UTC by Jaehyeon1020

- 기존 client 앱에 있던 admin contest api를 admin 앱에서 다시 구현한다.
- RestAPI => GraphQL로 다시 작성한다.

### Description

- client 앱에 있던 admin contest api 코드 참고해서 admin 앱에 GraphQL로 다시 구현했습니다.

### Additional context
- Admin 서버는 이미 권한을 갖고 있는 유저만 접근이 가능하게 한다고 들어서, client 앱에서 있었던 권한 관련 Guard는 없애고 구현했습니다.
---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-06-27 12:38 UTC, dotoleeoak commented
Close하는 이슈도 description에 남겨주세요!
(예: Close #100)

2023-06-27 13:03 UTC, dotoleeoak commented
@jspark2000 리뷰 부탁드려요...!

2023-07-03 12:01 UTC, aintbe requested changes
코멘트의 많은 부분이 #589 와 연관되어 있어서, 먼저 main 브랜치 merge하고 리뷰 확인해주세요!!

2023-07-31 15:15 UTC, cho-to commented on backend/apps/admin/src/contest/model/input.input.ts
> +  @Field(() => ID, { nullable: false })
제 생각엔 여기서 `ID` field 대신에 `int`로 설정해도 괜찮을 것 같은데 어떠세요?!
왜냐하면, graphql 공식문서에서

> The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String; however, defining it as an ID signifies that it is not intended to be human‐readable.

라고 적혀있는데, groupId는 사람이 읽을 수 있는 `Int` 형태니까 ID로 표시해주지 않아도 괜찮을 것 같아서요!

2023-07-31 15:19 UTC, cho-to commented on backend/apps/admin/src/contest/contest.resolver.ts
> +    @Args('input') input: ContestInput
별건 아닌데 `CreateContestInput` 이라고 수정하면 어떨까요? 위 `getContests` 에서도 `GetContestsInput `이라고 수정해서 `contest.input.ts` 파일에 함께 넣어도 깔끔할 것 같아요 ~!

2023-07-31 15:23 UTC, cho-to commented on backend/apps/admin/src/contest/model/input.input.ts
> +  @Field(() => ID, { nullable: false })
만약 `Int` 로 한다면 `resolver`에서도 `parseInt`를 하지 않아도 될 것 같아요!

2023-07-31 15:49 UTC, cho-to commented on backend/apps/admin/src/contest/contest.resolver.ts
> +    @Args('input') input: InputForDetail
혹시 궁금한건데 `Args`로 받아오는 `groupId`랑 `InputForDetail`에서 받아오는 `groupId`랑 다른걸까요?!
만약 같다면, `InputForDetail`에서 `groupId`랑 `contestId`만 받아와서 `InputForDetail`을 사용하지 않아도 될것같아서요!

2023-07-31 15:52 UTC, cho-to commented on backend/apps/admin/src/contest/model/input-for-detail.input.ts
> +  itemId!: number
`itemId`보다 `contestId`로 수정하는게 읽기 더 쉬울 것 같아요!

2023-08-01 05:25 UTC, Jaehyeon1020 commented on backend/apps/admin/src/contest/contest.resolver.ts
> +    @Args('input') input: InputForDetail
두 groupId가 같은건 맞습니다. Global로 작동하는 GroupLeaderGuard가 작동하려면 인자에 groupId가 필요해 추가해두었습니다! (resolver 내부에서 사용은 하지 않아요)

2023-08-01 05:30 UTC, Jaehyeon1020 commented on backend/apps/admin/src/contest/contest.resolver.ts
> +  }
위에 적어주신 사항들 모두 반영했습니다 감사해요!!

2023-08-03 10:13 UTC, aintbe commented on backend/apps/admin/src/contest/contest.resolver.ts
> +  }
별 건 아니지만, contest 관련 API랑 publicizingRequest 관련 API를 한데 묶어놓는 게 보기 편할 것 같아요! 이 API 아래쪽으로 옮겨주세요~

2023-08-03 10:14 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +    if (groupId == 1) {
상수 말고 OPEN_SPACE_ID 사용해주세요!!

2023-08-03 10:16 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +        'request converting contest to be public'
'duplicated publicizing request', 'contest'가 더 적절할 것 같습니다!

2023-08-03 10:16 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +    return contest
return 타입은 `PublicizingRequest`인 게 좋을 것 같아요!

2023-08-05 07:11 UTC, aintbe commented on backend/apps/admin/src/contest/contest.resolver.ts
> +  async requestToPublic(
요거 이름 requestPublicizing으로 바꿔주세요!

2023-08-05 07:24 UTC, aintbe commented on backend/apps/admin/src/contest/contest.resolver.ts
> +    @Args('groupId', ParseIntPipe) groupId: number,
Open Space에 들어가 있을 때는 프론트엔드에서 그룹의 ID를 알지 못해서, `groupId` 값을 안 넣어줄 거예요! 그래서 아래처럼 항상 디폴트 값을 받도록 설정해주셔야 합니다ㅎㅎ

```suggestion
    @Args('groupId', { defaultValue: OPEN_SPACE_ID }, ParseIntPipe) groupId: number,
```

2023-08-05 07:25 UTC, aintbe commented on backend/apps/admin/src/contest/contest.resolver.ts
> +        console.log(error.message)
다른 모듈 참고하시면 logger를 private property로 정의해서, 그 로거로 로깅을 합니다! 다른 모듈 보고 바꿔주세요~

2023-08-05 08:04 UTC, aintbe requested changes

2023-08-05 08:04 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +    }
import API는 사용자가 선택한 특정한 problem만 contest에 넣어줘야 합니다! 아마 problem을 조회하는 건 problem 모듈에서 처리할 거고, 여기서는 사용자가 선택한 problem id를 받아서 넣는 것만 처리해주시면 돼요!
로직을 단계별로 설명하자면 (0) contestId와 problemIds: number[]를 인자로 받아서, (1) contest가 group에 존재하는지를 확인하고 (2) 각 problem이 해당 그룹에 존재하는지도 확인한 다음 (3) 확인된 problem을 contest에 넣어주는 게 되겠네요!

2023-08-05 08:05 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +  async importGroupProblemsToContest(groupId: number, contestId: number) {
이름 importProblems로 바꿔주세요!

2023-08-06 10:02 UTC, Jaehyeon1020 commented on backend/apps/admin/src/contest/contest.service.ts
> +    }
다 반영했습니다 감사해요 !!
근데 importProblems 함수에서 problem을 받을 때 problem이 해당 그룹 속해있는 문제가 아니면 예외를 던지는 걸로 구현하는게 맞을까요 아니면 건너뛰고 해당 그룹에 속해있는 문제만 걸러서 받는 걸로 하는게 맞을까요? 일단 후자로 구현해놓았습니다.

2023-08-06 11:03 UTC, Jaehyeon1020 commented on backend/apps/admin/src/contest/contest.service.ts
> +    }
+ thunder client docs는 곧 작성해서 올릴게요!

2023-08-10 12:16 UTC, cho-to commented on backend/apps/admin/src/contest/contest.service.ts
> +    }
저는 후자로 해도 괜찮을 것 같아요~ problem 조회할 때 group problem만 불러오기 때문에 굳이 할 필요는 없을 것 같은데 어떻게 생각하시나용

2023-08-10 12:22 UTC, Jaehyeon1020 commented on backend/apps/admin/src/contest/contest.service.ts
> +    }
좋아요~~ 회의에서도 후자로 하기로 했어요!

2023-08-10 12:34 UTC, cho-to commented on backend/apps/admin/src/contest/contest.service.ts
> +    }
아하 굿굿 ~~~~~!!

2023-08-10 12:52 UTC, cho-to commented on backend/apps/admin/src/contest/contest.service.spec.ts
> +    })
`cacheManager`도 mocking해주시면 더 좋을 것 같아요!!
어떻게 mocking하는지는 https://github.com/skkuding/codedang/blob/main/backend/apps/client/src/group/group.service.spec.ts
를 참고하시면 도움되실 것 같습니다!!

2023-08-15 08:20 UTC, cho-to commented on backend/prisma/schema.prisma
> +  // emitCompiled       = true
호옥시 여기는 왜 추가하셨는지 여쭤봐도 괜찮을까요?

2023-08-16 04:57 UTC, cho-to commented on backend/prisma/schema.prisma
> +  // emitCompiled       = true
아하아하!! 궁금해서 여쭤봤어요! 알려주셔서 감사합니당

2023-08-16 05:48 UTC, cho-to commented on backend/apps/admin/src/contest/contest.service.ts
> +    return updatedContest
혹시 제 생각에는 `publicizingRequestKey`가 존재하는지 검사하고, `contest`를 `update`하는게 더 괜찮을 것 같은데 어떻게 생각하시나요?
왜냐하면, 만약 key가 cache에 존재하지 않는 경우에도 contest는 open_space로 update 되니까요 !

2023-08-17 00:50 UTC, Jaehyeon1020 commented on backend/apps/admin/src/contest/contest.service.ts
> +    return updatedContest
네 저 코드대로면 contest를 수정해버리고 key에 대한 검사를 하는게 되네요 ㅠㅠ 수정하겠습니다 !!

2023-08-24 10:43 UTC, aintbe requested changes

2023-08-24 10:43 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +  }
지난번에 모든 publicizing request를 'publicize'라는 하나의 키에 대한 배열 값으로 저장하고, 오래된 request를 없앨 수 있도록 expireTime을 만들어놓기로 했는데, 후자만 반영되고 전자가 반영이 안 된 것 같아요! 이를 반영해서 GET 함수는
1. `publicize` 키로 배열 가져오기
2. 배열에서 expireTime이 현재 시간(new Date())보다 이전인 아이템 지우기
3. 수정된 배열을 다시 캐시에 set하고(수정된 게 없으면 스킵)
4. 수정된 배열 return

이렇게 수정해주시면 될 것 같습니다! 그리고 이건 다른 질문인데 expireTime을 저렇게 다시 설정해주신 이유가 있나요?

2023-08-24 10:43 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +    await this.cacheManager.del(key)
accept와 reject는 배열 가지고 와서 맞는 contestId를 찾고, 있으면 그것 제거하고 새로 set하는 식으로 바꿔주세요!

2023-08-24 10:43 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +    }
groupId 체크하는 건 prisma에서 갖고 오는 부분에서 where문으로 해결해주시면 좋을 것 같아요! 다른 코드에서도 그렇게 하고 있어서 통일감을 줄 수 있기도 하고, 유저가 접근할 수 없는 오브젝트라면 존재를 알려주지도 않는 것(EntityNotExist)이 보안상으로도 더 적절해서요ㅎㅎ

2023-08-24 10:43 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +    )
여기도 배열에 추가해서 새로 set하도록 해주세요~

2023-08-26 07:19 UTC, Jaehyeon1020 commented on backend/apps/admin/src/contest/contest.service.ts
> +    )
전부 반영했어요~~!! 감사합니다

2023-09-21 09:23 UTC, Jaehyeon1020 commented on backend/apps/admin/src/contest/contest.resolver.ts
> +  async updateContest(
반영했습니다 !!

2023-09-21 12:19 UTC, aintbe requested changes

2023-09-21 12:19 UTC, aintbe commented on backend/apps/admin/src/contest/contest.resolver.ts
> +      this.logger.error(error.message, error.stack)
이 두 컨트롤러 하나로 합쳐도 되지 않을까요? (서비스도 마찬가지)

2023-09-21 12:19 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +    const requests = (await this.cacheManager.get(
혹시 이런 방식으로는 안 되나요? `this.cacheManager.get<PublicizingRequest[]>(key)`

2023-09-21 12:19 UTC, aintbe commented on backend/apps/admin/src/contest/contest.service.ts
> +    return contest
이런 과정은 굳이 넣지 않아도 될 것 같아요!

2023-09-21 12:32 UTC, cho-to commented on backend/apps/admin/src/contest/contest.resolver.ts
> +  @UseRolesGuard()
기획에 잘못적혀있었어요 . . . 죄송합니다 😢

2023-09-22 02:35 UTC, merged