feat(be): apply gql to admin group member
skkuding/codedang pull request #596
Opened 2023-07-04 05:38 UTC by Hyeongrok1

### Description

admin group member api를 구현합니다.

1. Group Manager/Member list
2. Group Manager Down/Upgrade
3. Delete Group Manager/Member
4. Group Member Needed approval
5. Reject/Accept Join

### Additional context

Test Code는 아직 다 작성하지 못했습니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-07-07 11:15 UTC, aintbe requested changes

2023-07-07 11:15 UTC, aintbe commented on backend/apps/admin/src/user/user.resolver.ts
> +    @Args('role', { type: () => Role }) role
일단 서비스의 권한 설정에 대해서 혼동이 있었던 것 같아 설명을 드리자면, 코드당에서는 시스템 롤과 그룹 롤이 구분되어 있습니다. 시스템 롤은 시스템 전반에서 유저의 권한을 결정해주고, 그룹 롤은 각각의 그룹 안에서 유저의 권한을 결정합니다. 시스템 롤에는 User, Manager, Admin, SuperAdmin이 있고, 그룹 롤에는 GroupMember, GroupLeader(그룹 관리자)가 있어요. 그리고 둘 사이에는 관계가 없습니다. 예를 들어 User 시스템 롤을 가진 사람이 어떤 그룹에서 GroupLeader를 맡고 있을 수도 있어요. 반대로 Manager가 어떤 그룹에 참여 중이지 않아서 해당 그룹에 접근조차 못 할 수도 있죠.

getMembers API는 특정 그룹의 멤버 목록을 보여주는 API입니다. 이 목록을 볼 수 있는 사람은 그 그룹의 관리자여야겠죠? 따라서 여기서는 시스템 롤이 중요한 게 아니라 그룹 롤이 중요해요. 그리고 유저가 주어진 group의 leader인지를 확인하는 로직은 위에서 말씀드렸듯이 전역 가드가 이미 처리하고 있어요. 결론적으로 말씀드리자면, 여기서는 유저의 롤을 알 필요가 없습니다.

그리고 설령 유저의 롤을 확인해야 하는 API가 있다고 하더라도, 절대로 프론트엔드로부터 role을 직접 입력받아서는 안 됩니다!! 실제 유저의 role이 넘어온다는 보장이 없으니까요. 사용자의 role이 무엇인지는 백엔드가 직접 검증해야 해요! 이걸 어떻게 하는지는 admin/group 모듈의 getGroups API를 읽어보시면 될 것 같습니다.

2023-07-07 11:15 UTC, aintbe commented on backend/apps/admin/src/user/user.resolver.ts
> +    @Args('role', { type: () => Role }) role
```suggestion
    @Args('groupId', { defaultValue: OPEN_SPACE_ID }, ParseIntPipe) groupId: number,
    @Args('cursor', CursorValidationPipe) cursor: number,
    @Args('take', ParseIntPipe) take: number
```
이걸 다 조합하면 이렇게 수정되면 되겠네요! 그리고 input 같이 GraphQL 스타일로 type을 지정해놓은 경우에는 `type` 옵션을 달 필요가 없어요. 이걸 다는 건 TS의 타입과 GraphQL 타입이 1:1로 매칭되지 않을 경우에 모호함을 해소해주기 위함이거든요!ㅎㅎ (e.g., number <-> Int/Float)

2023-07-07 11:15 UTC, aintbe commented on backend/apps/admin/src/user/user.resolver.ts
> +  downgradeGroupManager(
downgrade와 upgrade를 분리해놓으신 이유가 있을까요?

2023-07-07 11:15 UTC, aintbe commented on backend/apps/admin/src/user/user.resolver.ts
> +  acceptJoin(@Args('input') input: JoinInput): Promise<UserGroup> {
여기도 마찬가지로 reject와 accept를 분리해놓으신 이유가 있나요?

2023-07-07 11:15 UTC, aintbe commented on backend/apps/admin/src/user/user.resolver.ts
> +  getNeededApproval(
이름은 getJoinRequests, rejectJoinRequest, ... 등으로 통일하는 게 좋을 것 같아요!

2023-07-08 06:03 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.resolver.ts
> +    @Args('role', { type: () => Role }) role
리뷰해주신대로 수정완료했습니다!

2023-07-08 06:16 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.resolver.ts
> +  downgradeGroupManager(
지금 시점에서 코드 중복이 많아서 분리할 이유가 없을 것 같습니다. 수정하겠습니다.

2023-07-08 06:16 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.resolver.ts
> +  acceptJoin(@Args('input') input: JoinInput): Promise<UserGroup> {
마찬가지로 코드 중복을 줄이도록 하겠습니다.

2023-08-10 11:10 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
> +    }
`BadRequestException` 보다 `EntityNotExistException`으로 joinRequest가 존재하지 않습니다. 이런식으로 통일해도 괜찮을 것 같아요.

2023-08-10 11:10 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
> +    }
기획에서 User의 Role이 Admin, SuperAdmin이면 downgrade할 수 없어서 이점도 에러처리해주시면 감사하겠습니다 !!

2023-08-10 11:14 UTC, cho-to commented
그리고 `thunder client` 파일 중에서 필요없는 파일도 삭제해주시면 감사하겠습니다 !

2023-08-10 11:20 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
>        }
혹시 `graphql` 에서 선택해서 받을 수 있는데 `select` 문을 쓰신 이유가 있을까요?!

2023-08-10 11:41 UTC, cho-to commented on backend/apps/admin/src/user/user.service.spec.ts
> +    // cache = module.get<Cache>(CACHE_MANAGER)
`cache`도 mocking해서 test code 완성해주시면 감사하겠습니다 !!

2023-08-10 11:54 UTC, cho-to commented on backend/apps/admin/src/user/user.resolver.ts
> +  ): Promise<UpdateUserGroup> {
#686 에서 `Promise`를 다 지우고, (현재 vscode에서도 return type이 자동으로 명시되니까) logging을 구현해놨는데 혹시 읽어보시고 참고해주시면 좋을 것 같습니다 !
그리고 `Promise` 를 만약 없앤다면 `userGroup-update.model.ts`를 없애도 괜찮을 것 같습니다

2023-08-10 13:13 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
> +    }
#748 참조해주시면 감사하겠습니다 😄

2023-08-10 13:36 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
> +          },
혹시 궁금한 점이 있는데, `userId: true` 하지 않고 왜 `user`에서 꺼내오는지 알 수 있을까요??

2023-08-11 06:28 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
> +      })
혹시 번거로우시겠지만, `Role`이 `Admin`이거나 `SuperAdmin`이라면 가입승인과 동시에 `groupLeader`로 승격되어서 이 부분 반영해주실 수 있을까요..??

2023-08-12 04:00 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.service.ts
> +    }
알겠습니다!

2023-08-12 04:25 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.resolver.ts
> +  ): Promise<UpdateUserGroup> {
넵 promise 지우고 logging 추가하겠습니다

2023-08-12 04:50 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.service.ts
> +          },
생각을 해보니 꼭 그럴 이유는 없었을 것 같네요! 수정하겠습니다.

2023-08-24 13:23 UTC, aintbe requested changes

2023-08-24 13:23 UTC, aintbe commented on backend/apps/admin/src/user/user.resolver.ts
> +    @Args('isGroupLeader') isGroupLeader: boolean
멤버만 가져오는 함수, 리더만 가져오는 함수 두 가지를 분리하지 않고 재활용하려고 이 argument를 받아오도록 짜신 걸로 보이는데, 멤버 리스트를 가져올 때는 (리더를 제외한 멤버를 가져오는 게 아니라) 리더를 포함한 모든 멤버를 가져와야 해요! 요렇게 서비스 함수에서 로직 수정해주세요!

그리고 이해하기 쉽도록 argument 이름은 `leaderOnly`로 변경하고, default를 false로 설정해두면 좋을 것 같아요!

2023-08-24 13:23 UTC, aintbe commented on backend/apps/admin/src/user/user.resolver.ts
> +        false
upgrade & downgrade를 이렇게 처리할 거라면 mutation도 처음부터 하나로 통일하는 것도 괜찮을 것 같아요!

2023-08-24 13:23 UTC, aintbe commented on backend/apps/admin/src/user/user.resolver.ts
> +      return await this.userService.handleJoinRequest(groupId, userId, false)
이것도 마찬가지로 하나로 합칠 수 있을 것 같네욥!

2023-08-24 13:23 UTC, aintbe commented on backend/apps/admin/src/user/user.service.ts
> +        }),
cursor & skip 관련해서는 직관적으로 이해할 수 있도록 다른 코드와 방식을 통일하는 게 좋을 것 같아요..! 그리고 cursor가 0인 경우가 있어서 그 경우엔 문제가 생길 것 같네요ㅠㅠ

2023-08-24 13:23 UTC, aintbe commented on backend/apps/admin/src/user/user.resolver.ts
> +        throw new BadRequestException(error.message)
이건 서비스에서 ConflictFoundException -> 컨트롤러에서 ConflictException 리턴하도록 바꿔주세ㅛㅇ!

2023-08-24 13:23 UTC, aintbe commented on backend/apps/admin/src/user/user.service.ts
> +      await this.prisma.userGroup.findMany({
지금 방식은 모든 group member를 가져와서, (1) 유저가 그룹에 등록되어 있는지, (2) admin은 아닌지, (3) 이미 멤버이거나 리더이지 않은지를 매번 배열을 다 돌려서 확인하고 있어요! 만약에 한 번에 여러 유저의 롤을 변경할 거라면 이렇게 해야할 수도 있겠지만, 지금은 한 번에 한 명의 롤만 변경하고 있으니까, 처음부터 `userGroup.findUniqueOrThrow({ where: { userId_groupId: ... })`로 해당 유저의 정보를 받아와서, 이 userGroup에 대해 (1) (2) (3)을 체크하면 될 것 같아요.

2023-08-24 13:23 UTC, aintbe commented on backend/apps/admin/src/user/user.service.ts
> +        `userId ${userId} is not a group member of groupId ${groupId}`
이 경우에는 뮤테이션에서 ConflictException이 아닌 NotFoundException으로 처리해주는 게 더 적절할 것 같아요!

2023-08-24 13:23 UTC, aintbe commented on backend/apps/admin/src/user/user.service.ts
> +    isGroupLeader: boolean
이름이 isGroupLeader면 헷갈릴 수 있을 것 같은데, toGroupLeader로 바꾸면 더 좋을 것 같아요!

2023-08-24 13:23 UTC, aintbe commented on backend/apps/admin/src/user/user.service.ts
> +    }
요것도 conflictFoundException -> conflictException으로 변경해주세요~

2023-08-25 04:33 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.resolver.ts
> +  ): Promise<UpdateUserGroup> {
저번에 수정하고 push했는데 왜인지 반영이 안 되어 있네요... 금방 반영하겠습니다! 감사합니다.

2023-08-25 05:03 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.service.ts
> +    isGroupLeader: boolean
적절한 이름 같아요!

2023-08-28 10:24 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.service.ts
> +      await this.prisma.userGroup.findMany({
음 그런데 만약 manager의 수가 1명일 경우라면 downgrade를 막아야하는 상황인데 이 경우에는 다른 멤버들의 역할을 파악해야 하지 않을까요??

2023-08-28 10:45 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.service.ts
> +        }),
그런데 CursorValidationPipe을 거치면 cursor가 0일 경우 에러를 던지던데 혹시 어떤 식으로 cursor가 0이 될 수 있나요??

2023-08-28 10:46 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.service.ts
> +        }),
혹시 앞에서 말씀하신 것처럼 nullable 옵션을 추가하면 가능한 것인가요?!

2023-08-28 10:58 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/user.resolver.ts
> +        false
그렇네요 upgrade를 할지 downgrade 확인하기 위해 인자가 하나 더 필요할 텐데 혹시 어떤 이름이 적절할까요?

2023-08-30 07:44 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
> +      await this.prisma.userGroup.findMany({
GroupLeader 수 조회하는 것 때문에 1. 전체 group member를 받거나(DB 1회 접근) 2. userID&groupID 의 userGroup + GroupLeader 전체 조회해서 수 세기 (DB 2회 접근) 이렇게 될 것 같아요

2023-08-30 07:46 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
> +      await this.prisma.userGroup.findMany({
그리고 배열을 (1), (2), (3) 을 각각 따로 돌릴 필요없이
(1) 을 조회해서 만약 유저가 배열에 있다면 member를 return하게 하고,
(2) 는 위에서 return한 member.userRole을 통해 Role을 확인하고,
(3) 은 위에서 return한 member.isGroupLeader 를 통해 이미 멤버이거나 리더이지 않은지 확인하면
세번 따로 배열을 안 돌려도 되지 않을까요?!

2023-08-30 08:37 UTC, cho-to commented on backend/apps/admin/src/user/user.resolver.ts
> +        false
똑같이` toGroupLeader` 어떨까용

2023-08-30 09:43 UTC, aintbe commented on backend/apps/admin/src/user/user.service.ts
> +        }),
네네! nullable 옵션을 추가하면 클라이언트가 cursor 값을 설정하지 않고 요청을 보낼 수 있고, 그러면 CursorValidationPipe에서 cursor 값을 0으로 설정해줍니다. 클라이언트가 cursor 값을 설정하지 않았다는 건 이전에 GET list 요청을 보낸 적이 없어서 cursor 값을 모른다는 뜻이기 때문에, 서비스에서는 cursor=0을 받으면 그냥 맨 처음 레코드부터(i.e. cursor=1) take만큼 세서 보내주면 돼요!

2023-09-25 05:18 UTC, cho-to commented on backend/apps/admin/src/user/model/groupMember.model.ts
> +  userId: number
GrpahQL scalar 타입 중 `id` 타입은
> ID 스칼라 타입은 객체를 다시 요청하거나 캐시의 키로써 자주 사용되는 고유 식별자를 나타냅니다. ID 타입은 String 과 같은 방법으로 직렬화되지만, ID 로 정의하는 것은 사람이 읽을 수 있도록 하는 의도가 아니라는 것을 의미합니다. (https://graphql-kr.github.io/learn/schema)

라고 하는데, username과 userId같은 경우에는 사람이 읽을 수는 있으니까 `string` 타입이 조금 더 맞지 않을까 생각하는데 어떠세요...??

2023-09-25 06:07 UTC, cho-to commented on backend/apps/admin/src/user/user.resolver.ts
> +    @Args('accept') accept: boolean
service에서는 isAccepted인데 여기에서는 accept로 적혀있는 것 같아서 통일해주시면 감사하겠습니다 !

2023-09-25 06:46 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
> +    )
저 궁금한게 있는데 혹시 JOIN_GROUP_REQUEST_EXPIRE_TIME으로 set 하면 하나의 groupId에 대한 가입 요청들이 한꺼번에 expire_time이 재정의되는게 맞을까요??
만약 그렇다면 user의 가입요청별로 expire_time을 관리하는게 맞지않을까요..??

2023-11-12 02:09 UTC, dotoleeoak commented
@Jaehyeon1020 thunder client 지우고 bruno 추가해주면 좋을 거 같아요...!

2023-11-15 06:04 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/model/groupMember.model.ts
> +  name?: string
네 맞습니다!

2023-11-15 07:13 UTC, Hyeongrok1 commented on backend/apps/admin/src/user/model/groupMember.model.ts
> +  userId: number
넵 그게 더 적절해보입니다!

2023-12-27 16:09 UTC, cho-to commented on backend/apps/admin/src/user/user.service.ts
> +    )
구현해서 업데이트했습니다ㅏㅏㅏㅏㅏㅏ!ㅏ!!!

2023-12-27 16:13 UTC, cho-to commented
✔️ 현재 group에 대한 join Request들이 `[userId, timeLimit]`의 tuple들의 배열로 관리되어 있어 join Request들을 전체 조회하는 등 관련 API에서 timelimit이 지났는지 안지났는지 매번 filter해줘야 합니다...
- userId, groupId의 쌍으로 key를 설정하면 특정 groupID에 대한 전체 join Request들을 조회하는데에 어려움이 있습니다
-> 더 좋은 방안이 있거나, 생각난다면 바꿔도 좋을 듯 합니다.

2023-12-28 05:51 UTC, aintbe approved these changes

2023-12-28 05:51 UTC, merged