feat(fe): moved 526-group-main-api here, and added reload, fixed pagi…
skkuding/codedang pull request #612
Opened 2023-07-11 12:22 UTC by EliseCho13

…nation

### Description

Close #526 
moved 526-group-main-api PR to here
connected api of joining group, getting all groups, and my groups

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ o ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ o ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ o ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ o ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-07-20 11:33 UTC, dayongkr submitted a review, later dismissed

2023-08-01 08:43 UTC, eunnbi requested changes

2023-08-01 08:43 UTC, eunnbi commented on frontend/src/user/group/components/GroupListSection.vue
> +  if (!data.memberNum) router.push(`/group/${id}`)
`memberNum` 보다는 `isJoined` 값으로 소속 여부를 판단하는 것이 좋을 것 같아요!

2023-08-01 08:43 UTC, eunnbi commented on frontend/src/user/group/components/GroupListSection.vue
> +    if (!data.memberNum && !data.config.allowJoinFromSearch) {
여기도 `isJoined` 값을 사용하는 것이 좋을 것 같아요!

2023-08-01 08:43 UTC, eunnbi commented on frontend/src/user/group/components/GroupListSection.vue
> +                <p class="mb-4">{{ selectedGroup.memberNum || 1 }}</p>
`memberNum`이 0이면 그대로 0을 보여주는 것이 좋을 것 같아요

2023-08-01 08:58 UTC, eunnbi requested changes

2023-08-01 08:58 UTC, eunnbi commented on frontend/src/user/group/pages/[id].vue
> +interface Group {
응답이 아래와 같은 형식으로 오는데 타입도 맞춰서 수정해주세요!
```json
{
    "id": 2,
    "groupName": "Example Private Group",
    "description": "This is an example private group just for testing. Check if this group is not shown to users not registered to this group.",
    "isGroupLeader": false,
    "isJoined": true
}
```

2023-08-01 08:58 UTC, eunnbi commented on frontend/src/user/group/pages/[id].vue
> +    group.value = data
`isJoined` 값이 `false` 이면 페이지 이동하는 로직을 추가해주세요!

2023-08-01 09:03 UTC, eunnbi commented on frontend/src/user/group/components/GroupListSection.vue
>  type Group = {
여기도 API 응답에 따라서 타입 수정해주세요!

2023-08-01 09:04 UTC, eunnbi commented on frontend/src/user/group/components/GroupListSection.vue
> +type OneGroup = {
여기도 API 응답에 따라서 타입 수정해주세요!

2023-08-01 10:33 UTC, EliseCho13 commented on frontend/src/user/group/pages/[id].vue
> +interface Group {
수정 완료했고, memeber.vue도 맞춰서 수정해야 하는데 이는 PR#616에서 수정했습니다

2023-08-01 10:50 UTC, eunnbi requested changes

2023-08-01 10:50 UTC, eunnbi commented on frontend/src/user/group/components/GroupListSection.vue
> +    if (!data.isJoined && !data.allowJoinFromSearch) {
`join` API 응답에 `allowJoinFromSearch` 값이 없고 `isJoined`만 사용해서 `approval`이 필요한지 아닌지 구분하면 될 것 같아요

2023-08-01 11:17 UTC, eunnbi commented on frontend/src/user/group/components/GroupListSection.vue
> +const take = ref(5)
`group`이 5개보다 많을 때 `cursor`를 증가시키는 로직이 없어서 모든 group을 볼 수 없어요. 디자인 상으로 무한 스크롤이 어울려서 스크롤이 바닥에 닿을 때 `cursor`를 현재 리스트에 있는 그룹 중 가장 높은 `id`로 바꾸면 될 것 같아요!

2023-08-01 12:01 UTC, eunnbi commented on frontend/src/user/group/components/GroupListSection.vue
> +})
`target`이랑 `useIntersectionObserver` 지워주세요~

2023-08-10 13:30 UTC, eunnbi approved these changes

2023-08-10 13:30 UTC, merged