feat(be): implement admin workbook module with graphql
skkuding/codedang pull request #627
Opened 2023-07-13 17:49 UTC by gyunrinkle

### Description

- notion admin api 문서를 기반으로 graphql api를 구현
- Closes #516 

### Additional context

- 권한 부분을 잘 몰라서, Guard decorator를 없애고 구현했습니다.

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-08-01 13:47 UTC, aintbe requested changes
그리고 import 쪽에 problem ID가 실제로 존재하지 않을 경우와 problem이 해당 그룹에 속해 있지 않을 경우 고려해서 에러 핸들링 추가해주세요!!

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.resolver.ts
> +  async getWorkbookList(@Args('input') input: GetWorkbookListInput) {
이걸 다 조합한다고 하면 결과적으로는 이런 모양이 되겠네요:
```suggestion
  async getWorkbookList(
    @Args('groupId', { defaultValue: OPEN_SPACE_ID }, ParseIntPipe) groupId: number
    @Args('cursor', { nullable: true }, ValidationPipe) cursor: number,
    @Args('take', ParseIntPipe) take: number
  {
```

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.resolver.ts
> +    @Args('input') input: CreateWorkbookInput
여기도 마찬가지로 `groupId` 따로 받아주세요! 지금 처리하려는 요청이 그룹의 리더가 보낸 요청일 때만 처리해야 할 것 같다면 무조건 GroupLeaderGuard가 적용되어야 하고, 그러려면 인자로 groupId가 와야 합니다! 아래의 쿼리/뮤테이션도 모두 마찬가지예요 😄

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.resolver.ts
> +  async createWorkbook(
`@Query()`, `@Mutation()`의 name 옵션은 저희가 정의한 함수명과 다른 이름으로 요청을 받고 싶을 때 쿼리/뮤테이션명을 덮어쓰기 위해서 존재하는 옵션이에요. 지금은 이름이 같으니까 설정 안 해주셔도 됩니다.

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.resolver.ts
> +  async getWorkbookList(@Args('input') input: GetWorkbookListInput) {
그리고 네이밍 컨벤션이 있어서, 함수명 `getWorkbooks`로 바꿔주세요!  서비스 함수도 마찬가지입니당

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.resolver.ts
> +  async removeWorkbook(
얘도 네이밍 컨벤션 맞춰서 deleteWorkbook으로 바꿔주세요!

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.resolver.ts
> +  async getWorkbookDetail(
네이밍 컨벤션 맞춰서 getWorkbook으로 바꿔주세요! 서비스 함수도 마찬가지입니당

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.resolver.ts
> +    @Args('workbookId', { type: () => Int }, ParseIntPipe) id: number
`{ type: () => Int }`와 ParseIntPipe는 서로 같은 역할을 해요. 둘 중 하나만 써주세요!

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.resolver.ts
> +    @Args('workbookId', { type: () => Int }, ParseIntPipe) id: number
서로 다른 종류의 id를 받고 있는데 변수명을 idList, id로 하면 이해가 어려울 것 같아요. 데코레이터에 있는 argument 이름을 깔끔하게 잘 지으신 것 같은데 파라미터도 이 이름들로 통일하면 어떨까요??

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.resolver.ts
> +  async importProblemsInWorkbook(
함수가 워크북에 임포트된다는 사실은 쿼리 보낼 때 이미 알 수 있으니까, 이름은 그냥 importProblem으로 해도 될 것 같아요! 아니면 코드당 스키마에 WorkbookProblem이 있으니까, createWorkbookProblem도 괜찮을 것 같네요ㅎㅎㅎ

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.service.ts
> +      }
기획에 원래 태그까지 보여주도록 되어 있었나요??? 😮

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.service.ts
> +    })
GroupLeaderGuard는 유저가 `groupId`에 해당하는 그룹의 리더인지만을 확인해요. 그룹 1번에 워크북 1이 들어 있고, 유저가 그룹 2번의 리더라고 할게요. 이때 유저가 (groupId: 2, workbookId: 1)를 인자로 쿼리를 날리면, GroupLeaderGuard는 유저가 그룹 2의 리더니까 통과시킬 거예요. 그리고 서비스 함수에서는 유저가 찾고자 하는 워크북이 유저가 리더로 있는 그룹에 속한 것이 맞는지 확인해주지 않으니까, 어떤 그룹의 리더가 되면 그 그룹의 ID를 이용해서 다른 모든 그룹의 레코드를 조회할 수 있게 되겠죠?!

저희도 구현을 하던 중에 이 버그를 발견해서, 아마 참고하신 클라이언트 코드에 이 로직이 없었을 수 있는데, 이제는 넣어야 합니다!!🚀  where문에서 `groupId`도 함께 확인해주세요!

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.service.ts
> +      const { id, ...rest } = updateWorkbookInput
지금 rest는 버려지는 값이 아니라 실제로 사용될 값이니까, `data`처럼 좀 더 의미 있는 이름으로 지어주는 것도 괜찮을 것 같아요.

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.service.ts
> +    }
여기서는 update 전에 findFirst 쿼리를 보내서 먼저 해당 레코드가 존재하는지를 파악해주셔야 해요. 왜냐하면 위(getWorkbook)에서 말씀드렸던 거랑 똑같은 문제가 발생할 수 있거든요! 만약에 유저가 해당 그룹에 리더 권한이 없는데, 그냥 접근해서 존재하는 워크북을 막 삭제해버리면 안 되니까, 미리 id와 groupId를 조건으로 줘서 해당 그룹에 이 문제가 존재하는지를 파악을 하고, 없다면 그 부분에서 EntityNotExistsException을 throw해주는 게 맞습니다. 그러면 업데이트하려는 레코드가 존재하지 않는 경우는 앞쪽에서 미리 처리가 되니까, 굳이 try-catch문을 사용하지 않아도 되겠죠?
그리고 저희는 서비스 함수에서는 비즈니스 로직만을 구현하고 모든 에러 처리는 컨트롤러/리졸버에서 하는 것으로 통일을 해두었어요. 만약 만약에 이렇게 앞쪽에서 처리할 수 있는 상황이 아니어서 에러 핸들링을 해야 한다고 해도, 그런 코드는 컨트롤러/리졸버로 옮겨주세요~

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.service.ts
> +  async mapProblemstoWorkbook(
이것도 리졸버 함수명이랑 통일하는 게 좋을 것 같아요!

2023-08-01 13:47 UTC, aintbe commented on backend/apps/admin/src/workbook/workbook.service.ts
> +    for (const problemId of problemIds) {
여기도 마찬가지로 다른 로직 시작하기 전에 워크북이 그룹에 존재하는지부터 확인해주세요~ client/problem.service/getWorkbookProblem 참고하시면 좋을 것 같아요!

2023-08-03 11:01 UTC, gyunrinkle commented on backend/apps/admin/src/workbook/workbook.service.ts
> +      }
저도 잘 모르겠어요...

2023-08-03 11:41 UTC, gyunrinkle commented on .gitignore
> -!thunder-tests/environments/base.json
gitignore에서 저 라인들을 지우라는 말인가여?

2023-08-05 06:32 UTC, aintbe commented on .gitignore
> -!thunder-tests/environments/base.json
앗 지금 이 브랜치에서 저 라인이 지워져 있는데 있는 게 맞아서요! 다시 넣어주세욥~

2023-08-10 14:18 UTC, cho-to commented on backend/apps/admin/src/workbook/model/input/workbook.input.ts
> +export class UpdateWorkbookInput {
별건 아닌데 `workbook.input.ts`랑 `workbook.output.ts`를 같은 폴더(`model`)에다가 넣어놔도 괜찮을 것 같아요 ~!

2023-12-26 10:11 UTC, cho-to commented on backend/apps/client/src/clarification/clarification.service.ts
>            }
혹시 clarification 이름이 바뀌어서 announcement 맞게 수정해주실 수 있으실까요오

2024-08-18 14:14 UTC, closed without merging