feat(be): implement storing Contest/WorkbookProblem id in order field with graphql
skkuding/codedang pull request #819
Opened 2023-08-21 11:25 UTC by gyunrinkle

### Description

- contest-problem, workbook-problem res를 만들어, 각 res 안에서 Contest/WorkbookProblem id를 order field로 저장하는 로직을 구현
- Closes #744 

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-08-24 10:22 UTC, aintbe requested changes
그리고 contestProblem이랑 workbookProblem 내용이 겹쳐서, 그냥 problem 모듈에다가 개발하신 걸 옮기고 대신에 argument로 contestId or workbookId를 따로 받아올 수 있도록 하는 게 좋을 것 같아요!!

2023-08-24 10:22 UTC, aintbe commented on backend/apps/admin/src/workbook-problem/workbook-problem.service.ts
> +    }
등록된 problem의 개수가 0개인 경우는 존재할 수 있는 상황이라서 예외 처리 안 해주셔도 돼요!! 이것보다는 id를 받은 workbook이 현재 접속된 group에 속해있는지를 확인해주는 로직이 필요할 것 같네요!

2023-08-24 10:22 UTC, aintbe commented on backend/apps/admin/src/workbook-problem/workbook-problem.service.ts
> +    }
orders의 길이가 실제 problem 개수와 맞지 않는지는 아래에서 확인해주니까 이 로직은 없어도 될 것 같아요!

2023-08-24 10:22 UTC, aintbe commented on backend/apps/admin/src/workbook-problem/workbook-problem.service.ts
> +        return this.prisma.workbookProblem.update({
```ts
async (record, idx) => {
    ...
    return await this.prisma...
```
로 고쳐주세요!

2023-08-24 10:22 UTC, aintbe commented on backend/apps/admin/src/workbook-problem/workbook-problem.service.ts
> +        const newOrder = orders[idx]
orders의 인덱스를 problemId, 값을 각 problemId에 해당하는 order를 상정하고 개발하신 것 맞을까요? 이렇게 하면 problemId가 연속적이지 않거나 1부터 시작하지 않을 경우에 문제가 생길 수 있어서, 
예를 들어 problemId가 1, 2, 4인 workbookProblem이 있고, 1, 4, 2 순서로 보여주고 싶다면 orders=[1, 4, 2]로 보내는 것으로 변경하는 게 좋을 것 같아요!

2023-08-24 12:47 UTC, cho-to commented on backend/apps/admin/src/workbook-problem/workbook-problem.service.ts
> +    }
`contest` 도 마찬가지로 `groupId` 받아서 속해있는지 검사해주시면 좋을 것 같아용 
그리고 제 생각에는 `PrismaClientKnownRequestError` 를 직접 만들어서 던져주는 것보다는 `EntityNotExistException` 등의 에러를 바로 던져져도 좋을 것 같아요! Prisma 에러를 직접 만들어서 던져주면 clientVersion 맞춰 유지보수하기 어렵기두 하고 일반적인 EntityNotExistException을 사용해도 에러 내용 자체는 전달될 것 같아서요!

2023-09-28 20:58 UTC, gyunseo commented on backend/apps/admin/src/workbook-problem/workbook-problem.service.ts
> +        const newOrder = orders[idx]
오 그렇네요 알게씁니다!!

2023-09-28 21:19 UTC, gyunseo commented on backend/apps/admin/src/workbook-problem/workbook-problem.service.ts
> +        return this.prisma.workbookProblem.update({
넵

2023-09-28 21:23 UTC, gyunseo commented on backend/apps/admin/src/workbook-problem/workbook-problem.service.ts
> +    }
그렇네요!

2023-09-28 21:41 UTC, gyunseo commented on backend/apps/admin/src/workbook-problem/workbook-problem.service.ts
> +        const newOrder = orders[idx]
제가 생각한 것은 다음과 같습니다.
workbookId가 주어지면, 그 workbookId에 해당되는 workbookProblem을 다 긁어 옵니다.
그래서 예를 들어 그렇게 긁어 온  workbookProblem들의 problemId가 4, 8, 10이라고 가정을 합니다.
그리고, 그 친구들의 order field가 있을 거 잖아요? 그 order field를 orders로 준 array의 값들로 새로 갱신해주는 것입니다.
그래서 (problemId, order)로 표현하자면..
(4, 1)
(8, 2)
(10, 3)
의 레코드가 있다고 가정합니다. 그러면 order field가 작은 순서에서 큰 순서로 대로 front에서 보여주고, 만약에 그 보여주는 순서를 바꾸고 싶다면 극단적으로..
orders = [100, 1, 22] 로 주는 것이죠.
그러면
(4, 100)
(8, 1)
(10, 3)
으로 될 것이고, front에서는 order field가 작은 순서에서 큰 순서대로 8, 10, 4 순으로 보여주면 되고요.
혹시 이런 로직이 이상하다면 다르게 구현하도록 하겠습니다.

2023-12-26 06:38 UTC, JungangHighschool approved these changes
Excellent Work!

2023-12-26 07:16 UTC, merged