806 hiding unfinished ones
skkuding/codedang pull request #896
Opened 2023-09-25 01:24 UTC by EliseCho13

### Description

Close #806 

### Additional context

hide 키워드로 숨김처리한 코드부분을 표시하여 추후 복구가 쉽도록 함

Problem 페이지의 workbook,
헤더에서 contest, group 메뉴,
setting 페이지(누를 시 토스트 뜨게 함)
을 숨김처리함.

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-09-26 06:41 UTC, dotoleeoak requested changes

2023-09-26 06:41 UTC, dotoleeoak commented on docs/intro/frontend-preview.png
이 파일은 실수로 수정한 건가요?

2023-09-26 06:41 UTC, dotoleeoak commented on frontend/src/common/components/Organism/Header.vue
> +    return true
`return`은 필요 없을 거 같아요!

2023-09-26 06:41 UTC, dotoleeoak commented on pnpm-lock.yaml
이 파일도 원복해주세요...!

2023-10-01 23:07 UTC, EliseCho13 commented on docs/intro/frontend-preview.png
아 이건 제가 수동으로 한 건 아니고, 처음 브랜치 만들때 메인 풀 안된 상태로 만들어서인지 캐러셀이 저렇게 기존 캐러셀로 떠서 풀 받았었습니다. 아마 그때 이 변화가 생긴 거 같아요

2023-10-02 05:35 UTC, dotoleeoak approved these changes

2023-10-02 05:38 UTC, merged